// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AttributeInitParameters struct {

	// Whether this attribute is an array
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// The emoji to display alongside this attribute in chat messages, stored without colons
	Emoji *string `json:"emoji,omitempty" tf:"emoji,omitempty"`

	// Unique name of this attribute
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether this attribute is required. If this field is not set, the existing setting will be preserved.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// Engine resource name for this attribute
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AttributeObservation struct {

	// Whether this attribute is an array
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// The emoji to display alongside this attribute in chat messages, stored without colons
	Emoji *string `json:"emoji,omitempty" tf:"emoji,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Unique name of this attribute
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether this attribute is required. If this field is not set, the existing setting will be preserved.
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// Engine resource name for this attribute
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type AttributeParameters struct {

	// Whether this attribute is an array
	// +kubebuilder:validation:Optional
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// The emoji to display alongside this attribute in chat messages, stored without colons
	// +kubebuilder:validation:Optional
	Emoji *string `json:"emoji,omitempty" tf:"emoji,omitempty"`

	// Unique name of this attribute
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether this attribute is required. If this field is not set, the existing setting will be preserved.
	// +kubebuilder:validation:Optional
	Required *bool `json:"required,omitempty" tf:"required,omitempty"`

	// Engine resource name for this attribute
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// AttributeSpec defines the desired state of Attribute
type AttributeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AttributeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AttributeInitParameters `json:"initProvider,omitempty"`
}

// AttributeStatus defines the observed state of Attribute.
type AttributeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AttributeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Attribute is the Schema for the Attributes API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type Attribute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.array) || (has(self.initProvider) && has(self.initProvider.array))",message="spec.forProvider.array is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   AttributeSpec   `json:"spec"`
	Status AttributeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AttributeList contains a list of Attributes
type AttributeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Attribute `json:"items"`
}

// Repository type metadata.
var (
	Attribute_Kind             = "Attribute"
	Attribute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Attribute_Kind}.String()
	Attribute_KindAPIVersion   = Attribute_Kind + "." + CRDGroupVersion.String()
	Attribute_GroupVersionKind = CRDGroupVersion.WithKind(Attribute_Kind)
)

func init() {
	SchemeBuilder.Register(&Attribute{}, &AttributeList{})
}
