// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AttributesBindingArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AttributesBindingArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AttributesBindingArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AttributesBindingInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []AttributesBindingArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// Merge strategy for this attribute when alert updates. Possible values are: `first_wins`, `last_wins`, `append`, `max`, `min`.
	MergeStrategy *string `json:"mergeStrategy,omitempty" tf:"merge_strategy,omitempty"`

	// The literal or reference parameter value
	Value []AttributesBindingValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type AttributesBindingObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []AttributesBindingArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// Merge strategy for this attribute when alert updates. Possible values are: `first_wins`, `last_wins`, `append`, `max`, `min`.
	MergeStrategy *string `json:"mergeStrategy,omitempty" tf:"merge_strategy,omitempty"`

	// The literal or reference parameter value
	Value []AttributesBindingValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type AttributesBindingParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []AttributesBindingArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// Merge strategy for this attribute when alert updates. Possible values are: `first_wins`, `last_wins`, `append`, `max`, `min`.
	// +kubebuilder:validation:Optional
	MergeStrategy *string `json:"mergeStrategy,omitempty" tf:"merge_strategy,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []AttributesBindingValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type AttributesBindingValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AttributesBindingValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AttributesBindingValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AttributesInitParameters struct {

	// ID of the alert attribute to set with this binding
	AlertAttributeID *string `json:"alertAttributeId,omitempty" tf:"alert_attribute_id,omitempty"`

	Binding []AttributesBindingInitParameters `json:"binding,omitempty" tf:"binding,omitempty"`
}

type AttributesObservation struct {

	// ID of the alert attribute to set with this binding
	AlertAttributeID *string `json:"alertAttributeId,omitempty" tf:"alert_attribute_id,omitempty"`

	Binding []AttributesBindingObservation `json:"binding,omitempty" tf:"binding,omitempty"`
}

type AttributesParameters struct {

	// ID of the alert attribute to set with this binding
	// +kubebuilder:validation:Optional
	AlertAttributeID *string `json:"alertAttributeId" tf:"alert_attribute_id,omitempty"`

	// +kubebuilder:validation:Optional
	Binding []AttributesBindingParameters `json:"binding,omitempty" tf:"binding,omitempty"`
}

type BranchesBranchesConditionGroupsConditionsInitParameters struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []BranchesBranchesConditionGroupsConditionsParamBindingsInitParameters `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type BranchesBranchesConditionGroupsConditionsObservation struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []BranchesBranchesConditionGroupsConditionsParamBindingsObservation `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type BranchesBranchesConditionGroupsConditionsParamBindingsInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []BranchesConditionGroupsConditionsParamBindingsArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []BranchesConditionGroupsConditionsParamBindingsValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type BranchesBranchesConditionGroupsConditionsParamBindingsObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []BranchesConditionGroupsConditionsParamBindingsArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []BranchesConditionGroupsConditionsParamBindingsValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type BranchesBranchesConditionGroupsConditionsParamBindingsParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []BranchesConditionGroupsConditionsParamBindingsArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []BranchesConditionGroupsConditionsParamBindingsValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type BranchesBranchesConditionGroupsConditionsParameters struct {

	// The logical operation to be applied
	// +kubebuilder:validation:Optional
	Operation *string `json:"operation" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	// +kubebuilder:validation:Optional
	ParamBindings []BranchesBranchesConditionGroupsConditionsParamBindingsParameters `json:"paramBindings" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject" tf:"subject,omitempty"`
}

type BranchesBranchesConditionGroupsInitParameters struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []BranchesBranchesConditionGroupsConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type BranchesBranchesConditionGroupsObservation struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []BranchesBranchesConditionGroupsConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type BranchesBranchesConditionGroupsParameters struct {

	// The prerequisite conditions that must all be satisfied
	// +kubebuilder:validation:Optional
	Conditions []BranchesBranchesConditionGroupsConditionsParameters `json:"conditions" tf:"conditions,omitempty"`
}

type BranchesBranchesResultArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesBranchesResultArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesBranchesResultArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesBranchesResultInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []BranchesBranchesResultArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []BranchesBranchesResultValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type BranchesBranchesResultObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []BranchesBranchesResultArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []BranchesBranchesResultValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type BranchesBranchesResultParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []BranchesBranchesResultArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []BranchesBranchesResultValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type BranchesBranchesResultValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesBranchesResultValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesBranchesResultValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesConditionGroupsConditionsParamBindingsArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesConditionGroupsConditionsParamBindingsArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesConditionGroupsConditionsParamBindingsArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesConditionGroupsConditionsParamBindingsValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesConditionGroupsConditionsParamBindingsValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesConditionGroupsConditionsParamBindingsValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesReturnsInitParameters struct {

	// Whether the return value should be single or multi-value
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BranchesReturnsObservation struct {

	// Whether the return value should be single or multi-value
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type BranchesReturnsParameters struct {

	// Whether the return value should be single or multi-value
	// +kubebuilder:validation:Optional
	Array *bool `json:"array" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type DescriptionInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type DescriptionObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type DescriptionParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ElseBranchResultArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ElseBranchResultArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ElseBranchResultArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ElseBranchResultInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []ElseBranchResultArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []ElseBranchResultValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type ElseBranchResultObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []ElseBranchResultArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []ElseBranchResultValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type ElseBranchResultParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []ElseBranchResultArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []ElseBranchResultValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type ElseBranchResultValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ElseBranchResultValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ElseBranchResultValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ExpressionsElseBranchInitParameters struct {

	// The result assumed if the else branch is reached
	Result []ElseBranchResultInitParameters `json:"result,omitempty" tf:"result,omitempty"`
}

type ExpressionsElseBranchObservation struct {

	// The result assumed if the else branch is reached
	Result []ElseBranchResultObservation `json:"result,omitempty" tf:"result,omitempty"`
}

type ExpressionsElseBranchParameters struct {

	// The result assumed if the else branch is reached
	// +kubebuilder:validation:Optional
	Result []ElseBranchResultParameters `json:"result,omitempty" tf:"result,omitempty"`
}

type ExpressionsOperationsInitParameters struct {

	// An operation type that allows for a value to be set conditionally by a series of logical branches
	Branches []OperationsBranchesInitParameters `json:"branches,omitempty" tf:"branches,omitempty"`

	// An operation type that allows values to be filtered out by conditions
	Filter []OperationsFilterInitParameters `json:"filter,omitempty" tf:"filter,omitempty"`

	// An operation type that allows attributes of a type to be accessed by reference
	Navigate []OperationsNavigateInitParameters `json:"navigate,omitempty" tf:"navigate,omitempty"`

	// Indicates which operation type to execute
	OperationType *string `json:"operationType,omitempty" tf:"operation_type,omitempty"`

	// An operation type that allows a value to parsed from within a JSON object
	Parse []OperationsParseInitParameters `json:"parse,omitempty" tf:"parse,omitempty"`
}

type ExpressionsOperationsObservation struct {

	// An operation type that allows for a value to be set conditionally by a series of logical branches
	Branches []OperationsBranchesObservation `json:"branches,omitempty" tf:"branches,omitempty"`

	// An operation type that allows values to be filtered out by conditions
	Filter []OperationsFilterObservation `json:"filter,omitempty" tf:"filter,omitempty"`

	// An operation type that allows attributes of a type to be accessed by reference
	Navigate []OperationsNavigateObservation `json:"navigate,omitempty" tf:"navigate,omitempty"`

	// Indicates which operation type to execute
	OperationType *string `json:"operationType,omitempty" tf:"operation_type,omitempty"`

	// An operation type that allows a value to parsed from within a JSON object
	Parse []OperationsParseObservation `json:"parse,omitempty" tf:"parse,omitempty"`
}

type ExpressionsOperationsParameters struct {

	// An operation type that allows for a value to be set conditionally by a series of logical branches
	// +kubebuilder:validation:Optional
	Branches []OperationsBranchesParameters `json:"branches" tf:"branches,omitempty"`

	// An operation type that allows values to be filtered out by conditions
	// +kubebuilder:validation:Optional
	Filter []OperationsFilterParameters `json:"filter" tf:"filter,omitempty"`

	// An operation type that allows attributes of a type to be accessed by reference
	// +kubebuilder:validation:Optional
	Navigate []OperationsNavigateParameters `json:"navigate" tf:"navigate,omitempty"`

	// Indicates which operation type to execute
	// +kubebuilder:validation:Optional
	OperationType *string `json:"operationType" tf:"operation_type,omitempty"`

	// An operation type that allows a value to parsed from within a JSON object
	// +kubebuilder:validation:Optional
	Parse []OperationsParseParameters `json:"parse" tf:"parse,omitempty"`
}

type HTTPCustomOptionsInitParameters struct {

	// JSON path to extract the deduplication key from the payload
	DeduplicationKeyPath *string `json:"deduplicationKeyPath,omitempty" tf:"deduplication_key_path,omitempty"`

	// JavaScript expression that returns an object with all alert fields
	TransformExpression *string `json:"transformExpression,omitempty" tf:"transform_expression,omitempty"`
}

type HTTPCustomOptionsObservation struct {

	// JSON path to extract the deduplication key from the payload
	DeduplicationKeyPath *string `json:"deduplicationKeyPath,omitempty" tf:"deduplication_key_path,omitempty"`

	// JavaScript expression that returns an object with all alert fields
	TransformExpression *string `json:"transformExpression,omitempty" tf:"transform_expression,omitempty"`
}

type HTTPCustomOptionsParameters struct {

	// JSON path to extract the deduplication key from the payload
	// +kubebuilder:validation:Optional
	DeduplicationKeyPath *string `json:"deduplicationKeyPath" tf:"deduplication_key_path,omitempty"`

	// JavaScript expression that returns an object with all alert fields
	// +kubebuilder:validation:Optional
	TransformExpression *string `json:"transformExpression" tf:"transform_expression,omitempty"`
}

type HeartbeatOptionsInitParameters struct {

	// Number of consecutive missed pings before an alert fires.
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// How long after a missed ping before the heartbeat is considered late, in seconds. If zero, it transitions directly to failing.
	GracePeriodSeconds *float64 `json:"gracePeriodSeconds,omitempty" tf:"grace_period_seconds,omitempty"`

	// How often a ping is expected, in seconds.
	IntervalSeconds *float64 `json:"intervalSeconds,omitempty" tf:"interval_seconds,omitempty"`
}

type HeartbeatOptionsObservation struct {

	// Number of consecutive missed pings before an alert fires.
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// How long after a missed ping before the heartbeat is considered late, in seconds. If zero, it transitions directly to failing.
	GracePeriodSeconds *float64 `json:"gracePeriodSeconds,omitempty" tf:"grace_period_seconds,omitempty"`

	// How often a ping is expected, in seconds.
	IntervalSeconds *float64 `json:"intervalSeconds,omitempty" tf:"interval_seconds,omitempty"`

	// The URL to POST to in order to send a heartbeat ping.
	PingURL *string `json:"pingUrl,omitempty" tf:"ping_url,omitempty"`
}

type HeartbeatOptionsParameters struct {

	// Number of consecutive missed pings before an alert fires.
	// +kubebuilder:validation:Optional
	FailureThreshold *float64 `json:"failureThreshold,omitempty" tf:"failure_threshold,omitempty"`

	// How long after a missed ping before the heartbeat is considered late, in seconds. If zero, it transitions directly to failing.
	// +kubebuilder:validation:Optional
	GracePeriodSeconds *float64 `json:"gracePeriodSeconds,omitempty" tf:"grace_period_seconds,omitempty"`

	// How often a ping is expected, in seconds.
	// +kubebuilder:validation:Optional
	IntervalSeconds *float64 `json:"intervalSeconds" tf:"interval_seconds,omitempty"`
}

type JiraOptionsInitParameters struct {

	// Which projects in Jira should this alert source watch for new issues? IDs can either be IDs of the projects in Jira, or ID of catalog entries in the 'Jira Project' catalog type.
	ProjectIds []*string `json:"projectIds,omitempty" tf:"project_ids,omitempty"`
}

type JiraOptionsObservation struct {

	// Which projects in Jira should this alert source watch for new issues? IDs can either be IDs of the projects in Jira, or ID of catalog entries in the 'Jira Project' catalog type.
	ProjectIds []*string `json:"projectIds,omitempty" tf:"project_ids,omitempty"`
}

type JiraOptionsParameters struct {

	// Which projects in Jira should this alert source watch for new issues? IDs can either be IDs of the projects in Jira, or ID of catalog entries in the 'Jira Project' catalog type.
	// +kubebuilder:validation:Optional
	ProjectIds []*string `json:"projectIds,omitempty" tf:"project_ids,omitempty"`
}

type OperationsBranchesBranchesInitParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	ConditionGroups []BranchesBranchesConditionGroupsInitParameters `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`

	// The result assumed if the condition groups are satisfied
	Result []BranchesBranchesResultInitParameters `json:"result,omitempty" tf:"result,omitempty"`
}

type OperationsBranchesBranchesObservation struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	ConditionGroups []BranchesBranchesConditionGroupsObservation `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`

	// The result assumed if the condition groups are satisfied
	Result []BranchesBranchesResultObservation `json:"result,omitempty" tf:"result,omitempty"`
}

type OperationsBranchesBranchesParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	// +kubebuilder:validation:Optional
	ConditionGroups []BranchesBranchesConditionGroupsParameters `json:"conditionGroups" tf:"condition_groups,omitempty"`

	// The result assumed if the condition groups are satisfied
	// +kubebuilder:validation:Optional
	Result []BranchesBranchesResultParameters `json:"result,omitempty" tf:"result,omitempty"`
}

type OperationsBranchesInitParameters struct {

	// The branches to apply for this operation
	Branches []OperationsBranchesBranchesInitParameters `json:"branches,omitempty" tf:"branches,omitempty"`

	// The return type of an operation
	Returns []BranchesReturnsInitParameters `json:"returns,omitempty" tf:"returns,omitempty"`
}

type OperationsBranchesObservation struct {

	// The branches to apply for this operation
	Branches []OperationsBranchesBranchesObservation `json:"branches,omitempty" tf:"branches,omitempty"`

	// The return type of an operation
	Returns []BranchesReturnsObservation `json:"returns,omitempty" tf:"returns,omitempty"`
}

type OperationsBranchesParameters struct {

	// The branches to apply for this operation
	// +kubebuilder:validation:Optional
	Branches []OperationsBranchesBranchesParameters `json:"branches" tf:"branches,omitempty"`

	// The return type of an operation
	// +kubebuilder:validation:Optional
	Returns []BranchesReturnsParameters `json:"returns" tf:"returns,omitempty"`
}

type OperationsFilterConditionGroupsConditionsInitParameters struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []OperationsFilterConditionGroupsConditionsParamBindingsInitParameters `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type OperationsFilterConditionGroupsConditionsObservation struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []OperationsFilterConditionGroupsConditionsParamBindingsObservation `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type OperationsFilterConditionGroupsConditionsParamBindingsArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type OperationsFilterConditionGroupsConditionsParamBindingsArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type OperationsFilterConditionGroupsConditionsParamBindingsArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type OperationsFilterConditionGroupsConditionsParamBindingsInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []OperationsFilterConditionGroupsConditionsParamBindingsArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []OperationsFilterConditionGroupsConditionsParamBindingsValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type OperationsFilterConditionGroupsConditionsParamBindingsObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []OperationsFilterConditionGroupsConditionsParamBindingsArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []OperationsFilterConditionGroupsConditionsParamBindingsValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type OperationsFilterConditionGroupsConditionsParamBindingsParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []OperationsFilterConditionGroupsConditionsParamBindingsArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []OperationsFilterConditionGroupsConditionsParamBindingsValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type OperationsFilterConditionGroupsConditionsParamBindingsValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type OperationsFilterConditionGroupsConditionsParamBindingsValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type OperationsFilterConditionGroupsConditionsParamBindingsValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type OperationsFilterConditionGroupsConditionsParameters struct {

	// The logical operation to be applied
	// +kubebuilder:validation:Optional
	Operation *string `json:"operation" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	// +kubebuilder:validation:Optional
	ParamBindings []OperationsFilterConditionGroupsConditionsParamBindingsParameters `json:"paramBindings" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject" tf:"subject,omitempty"`
}

type OperationsFilterConditionGroupsInitParameters struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []OperationsFilterConditionGroupsConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type OperationsFilterConditionGroupsObservation struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []OperationsFilterConditionGroupsConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type OperationsFilterConditionGroupsParameters struct {

	// The prerequisite conditions that must all be satisfied
	// +kubebuilder:validation:Optional
	Conditions []OperationsFilterConditionGroupsConditionsParameters `json:"conditions" tf:"conditions,omitempty"`
}

type OperationsFilterInitParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	ConditionGroups []OperationsFilterConditionGroupsInitParameters `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`
}

type OperationsFilterObservation struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	ConditionGroups []OperationsFilterConditionGroupsObservation `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`
}

type OperationsFilterParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	// +kubebuilder:validation:Optional
	ConditionGroups []OperationsFilterConditionGroupsParameters `json:"conditionGroups" tf:"condition_groups,omitempty"`
}

type OperationsNavigateInitParameters struct {
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type OperationsNavigateObservation struct {
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type OperationsNavigateParameters struct {

	// +kubebuilder:validation:Optional
	Reference *string `json:"reference" tf:"reference,omitempty"`
}

type OperationsParseInitParameters struct {

	// The return type of an operation
	Returns []OperationsParseReturnsInitParameters `json:"returns,omitempty" tf:"returns,omitempty"`

	// The ES5 Javascript expression to execute
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type OperationsParseObservation struct {

	// The return type of an operation
	Returns []OperationsParseReturnsObservation `json:"returns,omitempty" tf:"returns,omitempty"`

	// The ES5 Javascript expression to execute
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type OperationsParseParameters struct {

	// The return type of an operation
	// +kubebuilder:validation:Optional
	Returns []OperationsParseReturnsParameters `json:"returns" tf:"returns,omitempty"`

	// The ES5 Javascript expression to execute
	// +kubebuilder:validation:Optional
	Source *string `json:"source" tf:"source,omitempty"`
}

type OperationsParseReturnsInitParameters struct {

	// Whether the return value should be single or multi-value
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type OperationsParseReturnsObservation struct {

	// Whether the return value should be single or multi-value
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type OperationsParseReturnsParameters struct {

	// Whether the return value should be single or multi-value
	// +kubebuilder:validation:Optional
	Array *bool `json:"array" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type SourceInitParameters struct {

	// Whether to auto-resolve incident alerts when the alert auto-resolves. Defaults to true. Only use in conjunction with auto_resolve_timeout_minutes.
	AutoResolveIncidentAlerts *bool `json:"autoResolveIncidentAlerts,omitempty" tf:"auto_resolve_incident_alerts,omitempty"`

	// When set, alerts from this source will automatically resolve after this many minutes.
	AutoResolveTimeoutMinutes *float64 `json:"autoResolveTimeoutMinutes,omitempty" tf:"auto_resolve_timeout_minutes,omitempty"`

	// Email address this alert source receives alerts to
	EmailAddress *string `json:"emailAddress,omitempty" tf:"email_address,omitempty"`

	HTTPCustomOptions []HTTPCustomOptionsInitParameters `json:"httpCustomOptions,omitempty" tf:"http_custom_options,omitempty"`

	HeartbeatOptions []HeartbeatOptionsInitParameters `json:"heartbeatOptions,omitempty" tf:"heartbeat_options,omitempty"`

	JiraOptions []JiraOptionsInitParameters `json:"jiraOptions,omitempty" tf:"jira_options,omitempty"`

	// Unique name of the alert source
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// IDs of teams that own this alert source
	// +listType=set
	OwningTeamIds []*string `json:"owningTeamIds,omitempty" tf:"owning_team_ids,omitempty"`

	// Type of alert source
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`

	Template []TemplateInitParameters `json:"template,omitempty" tf:"template,omitempty"`
}

type SourceObservation struct {

	// URL that can be used to send alert events to this source. This is only set for sources that accept webhook/HTTP events; email sources use the email_address field, and integration-based sources (like Jira) receive events through their native integrations.
	AlertEventsURL *string `json:"alertEventsUrl,omitempty" tf:"alert_events_url,omitempty"`

	// Whether to auto-resolve incident alerts when the alert auto-resolves. Defaults to true. Only use in conjunction with auto_resolve_timeout_minutes.
	AutoResolveIncidentAlerts *bool `json:"autoResolveIncidentAlerts,omitempty" tf:"auto_resolve_incident_alerts,omitempty"`

	// When set, alerts from this source will automatically resolve after this many minutes.
	AutoResolveTimeoutMinutes *float64 `json:"autoResolveTimeoutMinutes,omitempty" tf:"auto_resolve_timeout_minutes,omitempty"`

	// Email address this alert source receives alerts to
	EmailAddress *string `json:"emailAddress,omitempty" tf:"email_address,omitempty"`

	HTTPCustomOptions []HTTPCustomOptionsObservation `json:"httpCustomOptions,omitempty" tf:"http_custom_options,omitempty"`

	HeartbeatOptions []HeartbeatOptionsObservation `json:"heartbeatOptions,omitempty" tf:"heartbeat_options,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	JiraOptions []JiraOptionsObservation `json:"jiraOptions,omitempty" tf:"jira_options,omitempty"`

	// Unique name of the alert source
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// IDs of teams that own this alert source
	// +listType=set
	OwningTeamIds []*string `json:"owningTeamIds,omitempty" tf:"owning_team_ids,omitempty"`

	// Secret token used to authenticate this source, if applicable. If applicable, this is the token that must be included in either the query string or the 'Authorization' header when sending events to this alert source.
	SecretToken *string `json:"secretToken,omitempty" tf:"secret_token,omitempty"`

	// Type of alert source
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`

	Template []TemplateObservation `json:"template,omitempty" tf:"template,omitempty"`
}

type SourceParameters struct {

	// Whether to auto-resolve incident alerts when the alert auto-resolves. Defaults to true. Only use in conjunction with auto_resolve_timeout_minutes.
	// +kubebuilder:validation:Optional
	AutoResolveIncidentAlerts *bool `json:"autoResolveIncidentAlerts,omitempty" tf:"auto_resolve_incident_alerts,omitempty"`

	// When set, alerts from this source will automatically resolve after this many minutes.
	// +kubebuilder:validation:Optional
	AutoResolveTimeoutMinutes *float64 `json:"autoResolveTimeoutMinutes,omitempty" tf:"auto_resolve_timeout_minutes,omitempty"`

	// Email address this alert source receives alerts to
	// +kubebuilder:validation:Optional
	EmailAddress *string `json:"emailAddress,omitempty" tf:"email_address,omitempty"`

	// +kubebuilder:validation:Optional
	HTTPCustomOptions []HTTPCustomOptionsParameters `json:"httpCustomOptions,omitempty" tf:"http_custom_options,omitempty"`

	// +kubebuilder:validation:Optional
	HeartbeatOptions []HeartbeatOptionsParameters `json:"heartbeatOptions,omitempty" tf:"heartbeat_options,omitempty"`

	// +kubebuilder:validation:Optional
	JiraOptions []JiraOptionsParameters `json:"jiraOptions,omitempty" tf:"jira_options,omitempty"`

	// Unique name of the alert source
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// IDs of teams that own this alert source
	// +kubebuilder:validation:Optional
	// +listType=set
	OwningTeamIds []*string `json:"owningTeamIds,omitempty" tf:"owning_team_ids,omitempty"`

	// Type of alert source
	// +kubebuilder:validation:Optional
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`

	// +kubebuilder:validation:Optional
	Template []TemplateParameters `json:"template,omitempty" tf:"template,omitempty"`
}

type TemplateExpressionsInitParameters struct {

	// The else branch to resort to if all operations fail
	ElseBranch []ExpressionsElseBranchInitParameters `json:"elseBranch,omitempty" tf:"else_branch,omitempty"`

	// The human readable label of the expression
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The operations to execute in sequence for this expression
	Operations []ExpressionsOperationsInitParameters `json:"operations,omitempty" tf:"operations,omitempty"`

	// A short ID that can be used to reference the expression
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`

	// The root reference for this expression (i.e. where the expression starts)
	RootReference *string `json:"rootReference,omitempty" tf:"root_reference,omitempty"`
}

type TemplateExpressionsObservation struct {

	// The else branch to resort to if all operations fail
	ElseBranch []ExpressionsElseBranchObservation `json:"elseBranch,omitempty" tf:"else_branch,omitempty"`

	// The human readable label of the expression
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The operations to execute in sequence for this expression
	Operations []ExpressionsOperationsObservation `json:"operations,omitempty" tf:"operations,omitempty"`

	// A short ID that can be used to reference the expression
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`

	// The root reference for this expression (i.e. where the expression starts)
	RootReference *string `json:"rootReference,omitempty" tf:"root_reference,omitempty"`
}

type TemplateExpressionsParameters struct {

	// The else branch to resort to if all operations fail
	// +kubebuilder:validation:Optional
	ElseBranch []ExpressionsElseBranchParameters `json:"elseBranch,omitempty" tf:"else_branch,omitempty"`

	// The human readable label of the expression
	// +kubebuilder:validation:Optional
	Label *string `json:"label" tf:"label,omitempty"`

	// The operations to execute in sequence for this expression
	// +kubebuilder:validation:Optional
	Operations []ExpressionsOperationsParameters `json:"operations" tf:"operations,omitempty"`

	// A short ID that can be used to reference the expression
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference" tf:"reference,omitempty"`

	// The root reference for this expression (i.e. where the expression starts)
	// +kubebuilder:validation:Optional
	RootReference *string `json:"rootReference" tf:"root_reference,omitempty"`
}

type TemplateInitParameters struct {

	// Attributes to set on alerts coming from this source, with a binding describing how to set them.
	Attributes []AttributesInitParameters `json:"attributes,omitempty" tf:"attributes,omitempty"`

	Description []DescriptionInitParameters `json:"description,omitempty" tf:"description,omitempty"`

	// The expressions to be prepared for use by steps and conditions
	Expressions []TemplateExpressionsInitParameters `json:"expressions,omitempty" tf:"expressions,omitempty"`

	// Whether or not alerts produced by this source should be private
	IsPrivate *bool `json:"isPrivate,omitempty" tf:"is_private,omitempty"`

	Title []TitleInitParameters `json:"title,omitempty" tf:"title,omitempty"`

	VisibleToTeams []VisibleToTeamsInitParameters `json:"visibleToTeams,omitempty" tf:"visible_to_teams,omitempty"`
}

type TemplateObservation struct {

	// Attributes to set on alerts coming from this source, with a binding describing how to set them.
	Attributes []AttributesObservation `json:"attributes,omitempty" tf:"attributes,omitempty"`

	Description []DescriptionObservation `json:"description,omitempty" tf:"description,omitempty"`

	// The expressions to be prepared for use by steps and conditions
	Expressions []TemplateExpressionsObservation `json:"expressions,omitempty" tf:"expressions,omitempty"`

	// Whether or not alerts produced by this source should be private
	IsPrivate *bool `json:"isPrivate,omitempty" tf:"is_private,omitempty"`

	Title []TitleObservation `json:"title,omitempty" tf:"title,omitempty"`

	VisibleToTeams []VisibleToTeamsObservation `json:"visibleToTeams,omitempty" tf:"visible_to_teams,omitempty"`
}

type TemplateParameters struct {

	// Attributes to set on alerts coming from this source, with a binding describing how to set them.
	// +kubebuilder:validation:Optional
	Attributes []AttributesParameters `json:"attributes" tf:"attributes,omitempty"`

	// +kubebuilder:validation:Optional
	Description []DescriptionParameters `json:"description,omitempty" tf:"description,omitempty"`

	// The expressions to be prepared for use by steps and conditions
	// +kubebuilder:validation:Optional
	Expressions []TemplateExpressionsParameters `json:"expressions" tf:"expressions,omitempty"`

	// Whether or not alerts produced by this source should be private
	// +kubebuilder:validation:Optional
	IsPrivate *bool `json:"isPrivate,omitempty" tf:"is_private,omitempty"`

	// +kubebuilder:validation:Optional
	Title []TitleParameters `json:"title,omitempty" tf:"title,omitempty"`

	// +kubebuilder:validation:Optional
	VisibleToTeams []VisibleToTeamsParameters `json:"visibleToTeams,omitempty" tf:"visible_to_teams,omitempty"`
}

type TitleInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type TitleObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type TitleParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type VisibleToTeamsArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type VisibleToTeamsArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type VisibleToTeamsArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type VisibleToTeamsInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []VisibleToTeamsArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []VisibleToTeamsValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type VisibleToTeamsObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []VisibleToTeamsArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []VisibleToTeamsValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type VisibleToTeamsParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []VisibleToTeamsArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []VisibleToTeamsValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type VisibleToTeamsValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type VisibleToTeamsValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type VisibleToTeamsValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

// SourceSpec defines the desired state of Source
type SourceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SourceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SourceInitParameters `json:"initProvider,omitempty"`
}

// SourceStatus defines the observed state of Source.
type SourceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SourceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Source is the Schema for the Sources API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type Source struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.heartbeatOptions) || (has(self.initProvider) && has(self.initProvider.heartbeatOptions))",message="spec.forProvider.heartbeatOptions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.httpCustomOptions) || (has(self.initProvider) && has(self.initProvider.httpCustomOptions))",message="spec.forProvider.httpCustomOptions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sourceType) || (has(self.initProvider) && has(self.initProvider.sourceType))",message="spec.forProvider.sourceType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.template) || (has(self.initProvider) && has(self.initProvider.template))",message="spec.forProvider.template is a required parameter"
	Spec   SourceSpec   `json:"spec"`
	Status SourceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SourceList contains a list of Sources
type SourceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Source `json:"items"`
}

// Repository type metadata.
var (
	Source_Kind             = "Source"
	Source_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Source_Kind}.String()
	Source_KindAPIVersion   = Source_Kind + "." + CRDGroupVersion.String()
	Source_GroupVersionKind = CRDGroupVersion.WithKind(Source_Kind)
)

func init() {
	SchemeBuilder.Register(&Source{}, &SourceList{})
}
