// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AttributeValuesInitParameters struct {

	// The value of this element of the array, in a format suitable for this attribute type.
	ArrayValue []*string `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The value of this attribute, in a format suitable for this attribute type.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type AttributeValuesObservation struct {

	// The value of this element of the array, in a format suitable for this attribute type.
	ArrayValue []*string `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The value of this attribute, in a format suitable for this attribute type.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type AttributeValuesParameters struct {

	// The value of this element of the array, in a format suitable for this attribute type.
	// +kubebuilder:validation:Optional
	ArrayValue []*string `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The value of this attribute, in a format suitable for this attribute type.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CatalogEntriesInitParameters struct {

	// Map of external ID to entry in the catalog.
	Entries []EntriesInitParameters `json:"entries,omitempty" tf:"entries,omitempty"`

	// The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.io web UI.
	// +listType=set
	ManagedAttributes []*string `json:"managedAttributes,omitempty" tf:"managed_attributes,omitempty"`
}

type CatalogEntriesObservation struct {

	// Map of external ID to entry in the catalog.
	Entries []EntriesObservation `json:"entries,omitempty" tf:"entries,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.io web UI.
	// +listType=set
	ManagedAttributes []*string `json:"managedAttributes,omitempty" tf:"managed_attributes,omitempty"`
}

type CatalogEntriesParameters struct {

	// Map of external ID to entry in the catalog.
	// +kubebuilder:validation:Optional
	Entries []EntriesParameters `json:"entries,omitempty" tf:"entries,omitempty"`

	// The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.io web UI.
	// +kubebuilder:validation:Optional
	// +listType=set
	ManagedAttributes []*string `json:"managedAttributes,omitempty" tf:"managed_attributes,omitempty"`
}

type EntriesInitParameters struct {

	// Optional aliases that can be used to reference this entry
	Aliases []*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	AttributeValues []AttributeValuesInitParameters `json:"attributeValues,omitempty" tf:"attribute_values,omitempty"`

	// Name is the human readable name of this entry
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When catalog type is ranked, this is used to help order things
	Rank *float64 `json:"rank,omitempty" tf:"rank,omitempty"`
}

type EntriesObservation struct {

	// Optional aliases that can be used to reference this entry
	Aliases []*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	AttributeValues []AttributeValuesObservation `json:"attributeValues,omitempty" tf:"attribute_values,omitempty"`

	// ID of this catalog entry
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name is the human readable name of this entry
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When catalog type is ranked, this is used to help order things
	Rank *float64 `json:"rank,omitempty" tf:"rank,omitempty"`
}

type EntriesParameters struct {

	// Optional aliases that can be used to reference this entry
	// +kubebuilder:validation:Optional
	Aliases []*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// +kubebuilder:validation:Optional
	AttributeValues []AttributeValuesParameters `json:"attributeValues,omitempty" tf:"attribute_values,omitempty"`

	// Name is the human readable name of this entry
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// When catalog type is ranked, this is used to help order things
	// +kubebuilder:validation:Optional
	Rank *float64 `json:"rank,omitempty" tf:"rank,omitempty"`
}

// CatalogEntriesSpec defines the desired state of CatalogEntries
type CatalogEntriesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CatalogEntriesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CatalogEntriesInitParameters `json:"initProvider,omitempty"`
}

// CatalogEntriesStatus defines the observed state of CatalogEntries.
type CatalogEntriesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CatalogEntriesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CatalogEntries is the Schema for the CatalogEntriess API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type CatalogEntries struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CatalogEntriesSpec   `json:"spec"`
	Status            CatalogEntriesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CatalogEntriesList contains a list of CatalogEntriess
type CatalogEntriesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CatalogEntries `json:"items"`
}

// Repository type metadata.
var (
	CatalogEntries_Kind             = "CatalogEntries"
	CatalogEntries_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CatalogEntries_Kind}.String()
	CatalogEntries_KindAPIVersion   = CatalogEntries_Kind + "." + CRDGroupVersion.String()
	CatalogEntries_GroupVersionKind = CRDGroupVersion.WithKind(CatalogEntries_Kind)
)

func init() {
	SchemeBuilder.Register(&CatalogEntries{}, &CatalogEntriesList{})
}
