// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CatalogTypeInitParameters struct {

	// The categories that this type belongs to, to be shown in the web dashboard. Possible values are: `customer`, `issue-tracker`, `product-feature`, `service`, `on-call`, `team`, `user`.
	Categories []*string `json:"categories,omitempty" tf:"categories,omitempty"`

	// Human readble description of this type
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name is the human readable name of this type
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The url of the external repository where this type is managed. Users will not be able to edit the catalog type (or its entries) via the UI, and will instead be provided a link to this URL.
	SourceRepoURL *string `json:"sourceRepoUrl,omitempty" tf:"source_repo_url,omitempty"`

	// The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"]
	TypeName *string `json:"typeName,omitempty" tf:"type_name,omitempty"`

	// If enabled, you can refer to entries of this type by their name, as well as their external ID and any aliases.
	UseNameAsIdentifier *bool `json:"useNameAsIdentifier,omitempty" tf:"use_name_as_identifier,omitempty"`
}

type CatalogTypeObservation struct {

	// The categories that this type belongs to, to be shown in the web dashboard. Possible values are: `customer`, `issue-tracker`, `product-feature`, `service`, `on-call`, `team`, `user`.
	Categories []*string `json:"categories,omitempty" tf:"categories,omitempty"`

	// Human readble description of this type
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name is the human readable name of this type
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The url of the external repository where this type is managed. Users will not be able to edit the catalog type (or its entries) via the UI, and will instead be provided a link to this URL.
	SourceRepoURL *string `json:"sourceRepoUrl,omitempty" tf:"source_repo_url,omitempty"`

	// The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"]
	TypeName *string `json:"typeName,omitempty" tf:"type_name,omitempty"`

	// If enabled, you can refer to entries of this type by their name, as well as their external ID and any aliases.
	UseNameAsIdentifier *bool `json:"useNameAsIdentifier,omitempty" tf:"use_name_as_identifier,omitempty"`
}

type CatalogTypeParameters struct {

	// The categories that this type belongs to, to be shown in the web dashboard. Possible values are: `customer`, `issue-tracker`, `product-feature`, `service`, `on-call`, `team`, `user`.
	// +kubebuilder:validation:Optional
	Categories []*string `json:"categories,omitempty" tf:"categories,omitempty"`

	// Human readble description of this type
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name is the human readable name of this type
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The url of the external repository where this type is managed. Users will not be able to edit the catalog type (or its entries) via the UI, and will instead be provided a link to this URL.
	// +kubebuilder:validation:Optional
	SourceRepoURL *string `json:"sourceRepoUrl,omitempty" tf:"source_repo_url,omitempty"`

	// The type name of this catalog type, to be used when defining attributes. This is immutable once a CatalogType has been created. For non-externally sync types, it must follow the pattern Custom["SomeName"]
	// +kubebuilder:validation:Optional
	TypeName *string `json:"typeName,omitempty" tf:"type_name,omitempty"`

	// If enabled, you can refer to entries of this type by their name, as well as their external ID and any aliases.
	// +kubebuilder:validation:Optional
	UseNameAsIdentifier *bool `json:"useNameAsIdentifier,omitempty" tf:"use_name_as_identifier,omitempty"`
}

// CatalogTypeSpec defines the desired state of CatalogType
type CatalogTypeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CatalogTypeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CatalogTypeInitParameters `json:"initProvider,omitempty"`
}

// CatalogTypeStatus defines the observed state of CatalogType.
type CatalogTypeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CatalogTypeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CatalogType is the Schema for the CatalogTypes API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type CatalogType struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sourceRepoUrl) || (has(self.initProvider) && has(self.initProvider.sourceRepoUrl))",message="spec.forProvider.sourceRepoUrl is a required parameter"
	Spec   CatalogTypeSpec   `json:"spec"`
	Status CatalogTypeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CatalogTypeList contains a list of CatalogTypes
type CatalogTypeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CatalogType `json:"items"`
}

// Repository type metadata.
var (
	CatalogType_Kind             = "CatalogType"
	CatalogType_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CatalogType_Kind}.String()
	CatalogType_KindAPIVersion   = CatalogType_Kind + "." + CRDGroupVersion.String()
	CatalogType_GroupVersionKind = CRDGroupVersion.WithKind(CatalogType_Kind)
)

func init() {
	SchemeBuilder.Register(&CatalogType{}, &CatalogTypeList{})
}
