// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type EntryAttributeValuesInitParameters struct {

	// The value of this element of the array, in a format suitable for this attribute type.
	ArrayValue []*string `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The ID of this attribute, usually loaded from the incident_catalog_type_attribute resource.
	Attribute *string `json:"attribute,omitempty" tf:"attribute,omitempty"`

	// The value of this attribute, in a format suitable for this attribute type.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EntryAttributeValuesObservation struct {

	// The value of this element of the array, in a format suitable for this attribute type.
	ArrayValue []*string `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The ID of this attribute, usually loaded from the incident_catalog_type_attribute resource.
	Attribute *string `json:"attribute,omitempty" tf:"attribute,omitempty"`

	// The value of this attribute, in a format suitable for this attribute type.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EntryAttributeValuesParameters struct {

	// The value of this element of the array, in a format suitable for this attribute type.
	// +kubebuilder:validation:Optional
	ArrayValue []*string `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The ID of this attribute, usually loaded from the incident_catalog_type_attribute resource.
	// +kubebuilder:validation:Optional
	Attribute *string `json:"attribute" tf:"attribute,omitempty"`

	// The value of this attribute, in a format suitable for this attribute type.
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type EntryInitParameters struct {

	// Optional aliases that can be used to reference this entry
	Aliases []*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	AttributeValues []EntryAttributeValuesInitParameters `json:"attributeValues,omitempty" tf:"attribute_values,omitempty"`

	// ID of this catalog type
	CatalogTypeID *string `json:"catalogTypeId,omitempty" tf:"catalog_type_id,omitempty"`

	// An optional alternative ID for this entry, which is ensured to be unique for the type
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.io web UI. This enables partial management of entries owned by external systems (e.g., Schedules from the on-call product).
	// +listType=set
	ManagedAttributes []*string `json:"managedAttributes,omitempty" tf:"managed_attributes,omitempty"`

	// Name is the human readable name of this entry
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When catalog type is ranked, this is used to help order things
	Rank *float64 `json:"rank,omitempty" tf:"rank,omitempty"`
}

type EntryObservation struct {

	// Optional aliases that can be used to reference this entry
	Aliases []*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	AttributeValues []EntryAttributeValuesObservation `json:"attributeValues,omitempty" tf:"attribute_values,omitempty"`

	// ID of this catalog type
	CatalogTypeID *string `json:"catalogTypeId,omitempty" tf:"catalog_type_id,omitempty"`

	// An optional alternative ID for this entry, which is ensured to be unique for the type
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.io web UI. This enables partial management of entries owned by external systems (e.g., Schedules from the on-call product).
	// +listType=set
	ManagedAttributes []*string `json:"managedAttributes,omitempty" tf:"managed_attributes,omitempty"`

	// Name is the human readable name of this entry
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When catalog type is ranked, this is used to help order things
	Rank *float64 `json:"rank,omitempty" tf:"rank,omitempty"`
}

type EntryParameters struct {

	// Optional aliases that can be used to reference this entry
	// +kubebuilder:validation:Optional
	Aliases []*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// +kubebuilder:validation:Optional
	AttributeValues []EntryAttributeValuesParameters `json:"attributeValues,omitempty" tf:"attribute_values,omitempty"`

	// ID of this catalog type
	// +kubebuilder:validation:Optional
	CatalogTypeID *string `json:"catalogTypeId,omitempty" tf:"catalog_type_id,omitempty"`

	// An optional alternative ID for this entry, which is ensured to be unique for the type
	// +kubebuilder:validation:Optional
	ExternalID *string `json:"externalId,omitempty" tf:"external_id,omitempty"`

	// The set of attributes that are managed by this resource. By default, all attributes are managed by this resource.io web UI. This enables partial management of entries owned by external systems (e.g., Schedules from the on-call product).
	// +kubebuilder:validation:Optional
	// +listType=set
	ManagedAttributes []*string `json:"managedAttributes,omitempty" tf:"managed_attributes,omitempty"`

	// Name is the human readable name of this entry
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When catalog type is ranked, this is used to help order things
	// +kubebuilder:validation:Optional
	Rank *float64 `json:"rank,omitempty" tf:"rank,omitempty"`
}

// EntrySpec defines the desired state of Entry
type EntrySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EntryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EntryInitParameters `json:"initProvider,omitempty"`
}

// EntryStatus defines the observed state of Entry.
type EntryStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EntryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Entry is the Schema for the Entrys API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type Entry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.attributeValues) || (has(self.initProvider) && has(self.initProvider.attributeValues))",message="spec.forProvider.attributeValues is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.catalogTypeId) || (has(self.initProvider) && has(self.initProvider.catalogTypeId))",message="spec.forProvider.catalogTypeId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   EntrySpec   `json:"spec"`
	Status EntryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EntryList contains a list of Entrys
type EntryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Entry `json:"items"`
}

// Repository type metadata.
var (
	Entry_Kind             = "Entry"
	Entry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Entry_Kind}.String()
	Entry_KindAPIVersion   = Entry_Kind + "." + CRDGroupVersion.String()
	Entry_GroupVersionKind = CRDGroupVersion.WithKind(Entry_Kind)
)

func init() {
	SchemeBuilder.Register(&Entry{}, &EntryList{})
}
