// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TypeAttributeInitParameters struct {

	// Whether this attribute is an array or scalar.
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// If this is a backlink, the id of the attribute that it's linked from
	BacklinkAttribute *string `json:"backlinkAttribute,omitempty" tf:"backlink_attribute,omitempty"`

	// ID of this catalog type
	CatalogTypeID *string `json:"catalogTypeId,omitempty" tf:"catalog_type_id,omitempty"`

	// The name of this attribute.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// If this is a path attribute, the path that we should use to pull the data
	Path []*string `json:"path,omitempty" tf:"path,omitempty"`

	// Values for this attribute can be managed from the incident.io web dashboard.
	SchemaOnly *bool `json:"schemaOnly,omitempty" tf:"schema_only,omitempty"`

	// The type of this attribute.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TypeAttributeObservation struct {

	// Whether this attribute is an array or scalar.
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// If this is a backlink, the id of the attribute that it's linked from
	BacklinkAttribute *string `json:"backlinkAttribute,omitempty" tf:"backlink_attribute,omitempty"`

	// ID of this catalog type
	CatalogTypeID *string `json:"catalogTypeId,omitempty" tf:"catalog_type_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of this attribute.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// If this is a path attribute, the path that we should use to pull the data
	Path []*string `json:"path,omitempty" tf:"path,omitempty"`

	// Values for this attribute can be managed from the incident.io web dashboard.
	SchemaOnly *bool `json:"schemaOnly,omitempty" tf:"schema_only,omitempty"`

	// The type of this attribute.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TypeAttributeParameters struct {

	// Whether this attribute is an array or scalar.
	// +kubebuilder:validation:Optional
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// If this is a backlink, the id of the attribute that it's linked from
	// +kubebuilder:validation:Optional
	BacklinkAttribute *string `json:"backlinkAttribute,omitempty" tf:"backlink_attribute,omitempty"`

	// ID of this catalog type
	// +kubebuilder:validation:Optional
	CatalogTypeID *string `json:"catalogTypeId,omitempty" tf:"catalog_type_id,omitempty"`

	// The name of this attribute.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// If this is a path attribute, the path that we should use to pull the data
	// +kubebuilder:validation:Optional
	Path []*string `json:"path,omitempty" tf:"path,omitempty"`

	// Values for this attribute can be managed from the incident.io web dashboard.
	// +kubebuilder:validation:Optional
	SchemaOnly *bool `json:"schemaOnly,omitempty" tf:"schema_only,omitempty"`

	// The type of this attribute.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// TypeAttributeSpec defines the desired state of TypeAttribute
type TypeAttributeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TypeAttributeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TypeAttributeInitParameters `json:"initProvider,omitempty"`
}

// TypeAttributeStatus defines the observed state of TypeAttribute.
type TypeAttributeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TypeAttributeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TypeAttribute is the Schema for the TypeAttributes API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type TypeAttribute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.catalogTypeId) || (has(self.initProvider) && has(self.initProvider.catalogTypeId))",message="spec.forProvider.catalogTypeId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   TypeAttributeSpec   `json:"spec"`
	Status TypeAttributeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TypeAttributeList contains a list of TypeAttributes
type TypeAttributeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TypeAttribute `json:"items"`
}

// Repository type metadata.
var (
	TypeAttribute_Kind             = "TypeAttribute"
	TypeAttribute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TypeAttribute_Kind}.String()
	TypeAttribute_KindAPIVersion   = TypeAttribute_Kind + "." + CRDGroupVersion.String()
	TypeAttribute_GroupVersionKind = CRDGroupVersion.WithKind(TypeAttribute_Kind)
)

func init() {
	SchemeBuilder.Register(&TypeAttribute{}, &TypeAttributeList{})
}
