// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesBranchesInitParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	ConditionGroups []BranchesConditionGroupsInitParameters `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`

	// The result assumed if the condition groups are satisfied
	Result []BranchesResultInitParameters `json:"result,omitempty" tf:"result,omitempty"`
}

type BranchesBranchesObservation struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	ConditionGroups []BranchesConditionGroupsObservation `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`

	// The result assumed if the condition groups are satisfied
	Result []BranchesResultObservation `json:"result,omitempty" tf:"result,omitempty"`
}

type BranchesBranchesParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	// +kubebuilder:validation:Optional
	ConditionGroups []BranchesConditionGroupsParameters `json:"conditionGroups" tf:"condition_groups,omitempty"`

	// The result assumed if the condition groups are satisfied
	// +kubebuilder:validation:Optional
	Result []BranchesResultParameters `json:"result,omitempty" tf:"result,omitempty"`
}

type BranchesConditionGroupsInitParameters struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []ConditionGroupsConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type BranchesConditionGroupsObservation struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []ConditionGroupsConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type BranchesConditionGroupsParameters struct {

	// The prerequisite conditions that must all be satisfied
	// +kubebuilder:validation:Optional
	Conditions []ConditionGroupsConditionsParameters `json:"conditions" tf:"conditions,omitempty"`
}

type BranchesInitParameters struct {

	// The branches to apply for this operation
	Branches []BranchesBranchesInitParameters `json:"branches,omitempty" tf:"branches,omitempty"`

	// The return type of an operation
	Returns []ReturnsInitParameters `json:"returns,omitempty" tf:"returns,omitempty"`
}

type BranchesObservation struct {

	// The branches to apply for this operation
	Branches []BranchesBranchesObservation `json:"branches,omitempty" tf:"branches,omitempty"`

	// The return type of an operation
	Returns []ReturnsObservation `json:"returns,omitempty" tf:"returns,omitempty"`
}

type BranchesParameters struct {

	// The branches to apply for this operation
	// +kubebuilder:validation:Optional
	Branches []BranchesBranchesParameters `json:"branches" tf:"branches,omitempty"`

	// The return type of an operation
	// +kubebuilder:validation:Optional
	Returns []ReturnsParameters `json:"returns" tf:"returns,omitempty"`
}

type BranchesResultArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesResultArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesResultArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesResultInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []BranchesResultArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []BranchesResultValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type BranchesResultObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []BranchesResultArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []BranchesResultValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type BranchesResultParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []BranchesResultArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []BranchesResultValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type BranchesResultValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesResultValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type BranchesResultValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ConditionGroupsConditionsInitParameters struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []ConditionsParamBindingsInitParameters `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type ConditionGroupsConditionsObservation struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []ConditionsParamBindingsObservation `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type ConditionGroupsConditionsParamBindingsInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []ConditionsParamBindingsArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []ConditionsParamBindingsValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type ConditionGroupsConditionsParamBindingsObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []ConditionsParamBindingsArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []ConditionsParamBindingsValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type ConditionGroupsConditionsParamBindingsParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []ConditionsParamBindingsArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []ConditionsParamBindingsValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type ConditionGroupsConditionsParameters struct {

	// The logical operation to be applied
	// +kubebuilder:validation:Optional
	Operation *string `json:"operation" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	// +kubebuilder:validation:Optional
	ParamBindings []ConditionsParamBindingsParameters `json:"paramBindings" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject" tf:"subject,omitempty"`
}

type ConditionGroupsInitParameters struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []ConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type ConditionGroupsObservation struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []ConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type ConditionGroupsParameters struct {

	// The prerequisite conditions that must all be satisfied
	// +kubebuilder:validation:Optional
	Conditions []ConditionsParameters `json:"conditions" tf:"conditions,omitempty"`
}

type ConditionsInitParameters struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []ParamBindingsInitParameters `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type ConditionsObservation struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []ParamBindingsObservation `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type ConditionsParamBindingsArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ConditionsParamBindingsArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ConditionsParamBindingsArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ConditionsParamBindingsInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []ParamBindingsArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []ParamBindingsValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type ConditionsParamBindingsObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []ParamBindingsArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []ParamBindingsValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type ConditionsParamBindingsParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []ParamBindingsArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []ParamBindingsValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type ConditionsParamBindingsValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ConditionsParamBindingsValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ConditionsParamBindingsValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ConditionsParameters struct {

	// The logical operation to be applied
	// +kubebuilder:validation:Optional
	Operation *string `json:"operation" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	// +kubebuilder:validation:Optional
	ParamBindings []ParamBindingsParameters `json:"paramBindings" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject" tf:"subject,omitempty"`
}

type DelayInitParameters struct {

	// If this workflow is delayed, whether the conditions should be rechecked between trigger firing and execution
	ConditionsApplyOverDelay *bool `json:"conditionsApplyOverDelay,omitempty" tf:"conditions_apply_over_delay,omitempty"`

	// Delay in seconds between trigger firing and running the workflow
	ForSeconds *float64 `json:"forSeconds,omitempty" tf:"for_seconds,omitempty"`
}

type DelayObservation struct {

	// If this workflow is delayed, whether the conditions should be rechecked between trigger firing and execution
	ConditionsApplyOverDelay *bool `json:"conditionsApplyOverDelay,omitempty" tf:"conditions_apply_over_delay,omitempty"`

	// Delay in seconds between trigger firing and running the workflow
	ForSeconds *float64 `json:"forSeconds,omitempty" tf:"for_seconds,omitempty"`
}

type DelayParameters struct {

	// If this workflow is delayed, whether the conditions should be rechecked between trigger firing and execution
	// +kubebuilder:validation:Optional
	ConditionsApplyOverDelay *bool `json:"conditionsApplyOverDelay" tf:"conditions_apply_over_delay,omitempty"`

	// Delay in seconds between trigger firing and running the workflow
	// +kubebuilder:validation:Optional
	ForSeconds *float64 `json:"forSeconds" tf:"for_seconds,omitempty"`
}

type ElseBranchInitParameters struct {

	// The result assumed if the else branch is reached
	Result []ResultInitParameters `json:"result,omitempty" tf:"result,omitempty"`
}

type ElseBranchObservation struct {

	// The result assumed if the else branch is reached
	Result []ResultObservation `json:"result,omitempty" tf:"result,omitempty"`
}

type ElseBranchParameters struct {

	// The result assumed if the else branch is reached
	// +kubebuilder:validation:Optional
	Result []ResultParameters `json:"result,omitempty" tf:"result,omitempty"`
}

type ExpressionsInitParameters struct {

	// The else branch to resort to if all operations fail
	ElseBranch []ElseBranchInitParameters `json:"elseBranch,omitempty" tf:"else_branch,omitempty"`

	// The human readable label of the expression
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The operations to execute in sequence for this expression
	Operations []OperationsInitParameters `json:"operations,omitempty" tf:"operations,omitempty"`

	// A short ID that can be used to reference the expression
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`

	// The root reference for this expression (i.e. where the expression starts)
	RootReference *string `json:"rootReference,omitempty" tf:"root_reference,omitempty"`
}

type ExpressionsObservation struct {

	// The else branch to resort to if all operations fail
	ElseBranch []ElseBranchObservation `json:"elseBranch,omitempty" tf:"else_branch,omitempty"`

	// The human readable label of the expression
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// The operations to execute in sequence for this expression
	Operations []OperationsObservation `json:"operations,omitempty" tf:"operations,omitempty"`

	// A short ID that can be used to reference the expression
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`

	// The root reference for this expression (i.e. where the expression starts)
	RootReference *string `json:"rootReference,omitempty" tf:"root_reference,omitempty"`
}

type ExpressionsParameters struct {

	// The else branch to resort to if all operations fail
	// +kubebuilder:validation:Optional
	ElseBranch []ElseBranchParameters `json:"elseBranch,omitempty" tf:"else_branch,omitempty"`

	// The human readable label of the expression
	// +kubebuilder:validation:Optional
	Label *string `json:"label" tf:"label,omitempty"`

	// The operations to execute in sequence for this expression
	// +kubebuilder:validation:Optional
	Operations []OperationsParameters `json:"operations" tf:"operations,omitempty"`

	// A short ID that can be used to reference the expression
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference" tf:"reference,omitempty"`

	// The root reference for this expression (i.e. where the expression starts)
	// +kubebuilder:validation:Optional
	RootReference *string `json:"rootReference" tf:"root_reference,omitempty"`
}

type FilterConditionGroupsConditionsInitParameters struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []ConditionGroupsConditionsParamBindingsInitParameters `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type FilterConditionGroupsConditionsObservation struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []ConditionGroupsConditionsParamBindingsObservation `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type FilterConditionGroupsConditionsParameters struct {

	// The logical operation to be applied
	// +kubebuilder:validation:Optional
	Operation *string `json:"operation" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	// +kubebuilder:validation:Optional
	ParamBindings []ConditionGroupsConditionsParamBindingsParameters `json:"paramBindings" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject" tf:"subject,omitempty"`
}

type FilterConditionGroupsInitParameters struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []FilterConditionGroupsConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type FilterConditionGroupsObservation struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []FilterConditionGroupsConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type FilterConditionGroupsParameters struct {

	// The prerequisite conditions that must all be satisfied
	// +kubebuilder:validation:Optional
	Conditions []FilterConditionGroupsConditionsParameters `json:"conditions" tf:"conditions,omitempty"`
}

type FilterInitParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	ConditionGroups []FilterConditionGroupsInitParameters `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`
}

type FilterObservation struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	ConditionGroups []FilterConditionGroupsObservation `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`
}

type FilterParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	// +kubebuilder:validation:Optional
	ConditionGroups []FilterConditionGroupsParameters `json:"conditionGroups" tf:"condition_groups,omitempty"`
}

type NavigateInitParameters struct {
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type NavigateObservation struct {
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type NavigateParameters struct {

	// +kubebuilder:validation:Optional
	Reference *string `json:"reference" tf:"reference,omitempty"`
}

type OperationsInitParameters struct {

	// An operation type that allows for a value to be set conditionally by a series of logical branches
	Branches []BranchesInitParameters `json:"branches,omitempty" tf:"branches,omitempty"`

	// An operation type that allows values to be filtered out by conditions
	Filter []FilterInitParameters `json:"filter,omitempty" tf:"filter,omitempty"`

	// An operation type that allows attributes of a type to be accessed by reference
	Navigate []NavigateInitParameters `json:"navigate,omitempty" tf:"navigate,omitempty"`

	// Indicates which operation type to execute
	OperationType *string `json:"operationType,omitempty" tf:"operation_type,omitempty"`

	// An operation type that allows a value to parsed from within a JSON object
	Parse []ParseInitParameters `json:"parse,omitempty" tf:"parse,omitempty"`
}

type OperationsObservation struct {

	// An operation type that allows for a value to be set conditionally by a series of logical branches
	Branches []BranchesObservation `json:"branches,omitempty" tf:"branches,omitempty"`

	// An operation type that allows values to be filtered out by conditions
	Filter []FilterObservation `json:"filter,omitempty" tf:"filter,omitempty"`

	// An operation type that allows attributes of a type to be accessed by reference
	Navigate []NavigateObservation `json:"navigate,omitempty" tf:"navigate,omitempty"`

	// Indicates which operation type to execute
	OperationType *string `json:"operationType,omitempty" tf:"operation_type,omitempty"`

	// An operation type that allows a value to parsed from within a JSON object
	Parse []ParseObservation `json:"parse,omitempty" tf:"parse,omitempty"`
}

type OperationsParameters struct {

	// An operation type that allows for a value to be set conditionally by a series of logical branches
	// +kubebuilder:validation:Optional
	Branches []BranchesParameters `json:"branches" tf:"branches,omitempty"`

	// An operation type that allows values to be filtered out by conditions
	// +kubebuilder:validation:Optional
	Filter []FilterParameters `json:"filter" tf:"filter,omitempty"`

	// An operation type that allows attributes of a type to be accessed by reference
	// +kubebuilder:validation:Optional
	Navigate []NavigateParameters `json:"navigate" tf:"navigate,omitempty"`

	// Indicates which operation type to execute
	// +kubebuilder:validation:Optional
	OperationType *string `json:"operationType" tf:"operation_type,omitempty"`

	// An operation type that allows a value to parsed from within a JSON object
	// +kubebuilder:validation:Optional
	Parse []ParseParameters `json:"parse" tf:"parse,omitempty"`
}

type ParamBindingsArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ParamBindingsArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ParamBindingsArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ParamBindingsInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []ArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []ValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type ParamBindingsObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []ArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []ValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type ParamBindingsParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []ArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []ValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type ParamBindingsValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ParamBindingsValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ParamBindingsValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ParseInitParameters struct {

	// The return type of an operation
	Returns []ParseReturnsInitParameters `json:"returns,omitempty" tf:"returns,omitempty"`

	// The ES5 Javascript expression to execute
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type ParseObservation struct {

	// The return type of an operation
	Returns []ParseReturnsObservation `json:"returns,omitempty" tf:"returns,omitempty"`

	// The ES5 Javascript expression to execute
	Source *string `json:"source,omitempty" tf:"source,omitempty"`
}

type ParseParameters struct {

	// The return type of an operation
	// +kubebuilder:validation:Optional
	Returns []ParseReturnsParameters `json:"returns" tf:"returns,omitempty"`

	// The ES5 Javascript expression to execute
	// +kubebuilder:validation:Optional
	Source *string `json:"source" tf:"source,omitempty"`
}

type ParseReturnsInitParameters struct {

	// Whether the return value should be single or multi-value
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ParseReturnsObservation struct {

	// Whether the return value should be single or multi-value
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ParseReturnsParameters struct {

	// Whether the return value should be single or multi-value
	// +kubebuilder:validation:Optional
	Array *bool `json:"array" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type ResultArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ResultArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ResultArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ResultInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []ResultArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []ResultValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type ResultObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []ResultArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []ResultValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type ResultParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []ResultArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []ResultValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type ResultValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ResultValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ResultValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ReturnsInitParameters struct {

	// Whether the return value should be single or multi-value
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ReturnsObservation struct {

	// Whether the return value should be single or multi-value
	Array *bool `json:"array,omitempty" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ReturnsParameters struct {

	// Whether the return value should be single or multi-value
	// +kubebuilder:validation:Optional
	Array *bool `json:"array" tf:"array,omitempty"`

	// Expected return type of this expression (what to try casting the result to)
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type StepsInitParameters struct {
	ForEach *string `json:"forEach,omitempty" tf:"for_each,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []StepsParamBindingsInitParameters `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`
}

type StepsObservation struct {
	ForEach *string `json:"forEach,omitempty" tf:"for_each,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []StepsParamBindingsObservation `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`
}

type StepsParamBindingsArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type StepsParamBindingsArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type StepsParamBindingsArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type StepsParamBindingsInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []StepsParamBindingsArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []StepsParamBindingsValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type StepsParamBindingsObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []StepsParamBindingsArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []StepsParamBindingsValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type StepsParamBindingsParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []StepsParamBindingsArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []StepsParamBindingsValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type StepsParamBindingsValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type StepsParamBindingsValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type StepsParamBindingsValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type StepsParameters struct {

	// +kubebuilder:validation:Optional
	ForEach *string `json:"forEach,omitempty" tf:"for_each,omitempty"`

	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Bindings for the operation parameters
	// +kubebuilder:validation:Optional
	ParamBindings []StepsParamBindingsParameters `json:"paramBindings" tf:"param_bindings,omitempty"`
}

type ValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type ValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type WorkflowInitParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	ConditionGroups []ConditionGroupsInitParameters `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`

	// Whether to continue executing the workflow if a step fails
	ContinueOnStepError *bool `json:"continueOnStepError,omitempty" tf:"continue_on_step_error,omitempty"`

	// Configuration controlling workflow delay behaviour
	Delay []DelayInitParameters `json:"delay,omitempty" tf:"delay,omitempty"`

	// The expressions to be prepared for use by steps and conditions
	Expressions []ExpressionsInitParameters `json:"expressions,omitempty" tf:"expressions,omitempty"`

	// Folder to display the workflow in
	Folder *string `json:"folder,omitempty" tf:"folder,omitempty"`

	// Whether to include private escalations
	IncludePrivateEscalations *bool `json:"includePrivateEscalations,omitempty" tf:"include_private_escalations,omitempty"`

	// Whether to include private incidents
	IncludePrivateIncidents *bool `json:"includePrivateIncidents,omitempty" tf:"include_private_incidents,omitempty"`

	// Name provided by the user when creating the workflow
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// This workflow will run 'once for' a list of references
	OnceFor []*string `json:"onceFor,omitempty" tf:"once_for,omitempty"`

	// Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.
	// +listType=set
	RunsOnIncidentModes []*string `json:"runsOnIncidentModes,omitempty" tf:"runs_on_incident_modes,omitempty"`

	// Which incidents should the workflow be applied to?. Possible values are: `newly_created`, `newly_created_and_active`.
	RunsOnIncidents *string `json:"runsOnIncidents,omitempty" tf:"runs_on_incidents,omitempty"`

	// The shortform used to trigger this workflow (only applicable for manual triggers)
	Shortform *string `json:"shortform,omitempty" tf:"shortform,omitempty"`

	// What state this workflow is in. Possible values are: `active`, `disabled`, `draft`, `error`.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Steps that are executed as part of the workflow
	Steps []StepsInitParameters `json:"steps,omitempty" tf:"steps,omitempty"`

	// Unique name of the trigger
	Trigger *string `json:"trigger,omitempty" tf:"trigger,omitempty"`
}

type WorkflowObservation struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	ConditionGroups []ConditionGroupsObservation `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`

	// Whether to continue executing the workflow if a step fails
	ContinueOnStepError *bool `json:"continueOnStepError,omitempty" tf:"continue_on_step_error,omitempty"`

	// Configuration controlling workflow delay behaviour
	Delay []DelayObservation `json:"delay,omitempty" tf:"delay,omitempty"`

	// The expressions to be prepared for use by steps and conditions
	Expressions []ExpressionsObservation `json:"expressions,omitempty" tf:"expressions,omitempty"`

	// Folder to display the workflow in
	Folder *string `json:"folder,omitempty" tf:"folder,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether to include private escalations
	IncludePrivateEscalations *bool `json:"includePrivateEscalations,omitempty" tf:"include_private_escalations,omitempty"`

	// Whether to include private incidents
	IncludePrivateIncidents *bool `json:"includePrivateIncidents,omitempty" tf:"include_private_incidents,omitempty"`

	// Name provided by the user when creating the workflow
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// This workflow will run 'once for' a list of references
	OnceFor []*string `json:"onceFor,omitempty" tf:"once_for,omitempty"`

	// Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.
	// +listType=set
	RunsOnIncidentModes []*string `json:"runsOnIncidentModes,omitempty" tf:"runs_on_incident_modes,omitempty"`

	// Which incidents should the workflow be applied to?. Possible values are: `newly_created`, `newly_created_and_active`.
	RunsOnIncidents *string `json:"runsOnIncidents,omitempty" tf:"runs_on_incidents,omitempty"`

	// The shortform used to trigger this workflow (only applicable for manual triggers)
	Shortform *string `json:"shortform,omitempty" tf:"shortform,omitempty"`

	// What state this workflow is in. Possible values are: `active`, `disabled`, `draft`, `error`.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Steps that are executed as part of the workflow
	Steps []StepsObservation `json:"steps,omitempty" tf:"steps,omitempty"`

	// Unique name of the trigger
	Trigger *string `json:"trigger,omitempty" tf:"trigger,omitempty"`
}

type WorkflowParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	// +kubebuilder:validation:Optional
	ConditionGroups []ConditionGroupsParameters `json:"conditionGroups,omitempty" tf:"condition_groups,omitempty"`

	// Whether to continue executing the workflow if a step fails
	// +kubebuilder:validation:Optional
	ContinueOnStepError *bool `json:"continueOnStepError,omitempty" tf:"continue_on_step_error,omitempty"`

	// Configuration controlling workflow delay behaviour
	// +kubebuilder:validation:Optional
	Delay []DelayParameters `json:"delay,omitempty" tf:"delay,omitempty"`

	// The expressions to be prepared for use by steps and conditions
	// +kubebuilder:validation:Optional
	Expressions []ExpressionsParameters `json:"expressions,omitempty" tf:"expressions,omitempty"`

	// Folder to display the workflow in
	// +kubebuilder:validation:Optional
	Folder *string `json:"folder,omitempty" tf:"folder,omitempty"`

	// Whether to include private escalations
	// +kubebuilder:validation:Optional
	IncludePrivateEscalations *bool `json:"includePrivateEscalations,omitempty" tf:"include_private_escalations,omitempty"`

	// Whether to include private incidents
	// +kubebuilder:validation:Optional
	IncludePrivateIncidents *bool `json:"includePrivateIncidents,omitempty" tf:"include_private_incidents,omitempty"`

	// Name provided by the user when creating the workflow
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// This workflow will run 'once for' a list of references
	// +kubebuilder:validation:Optional
	OnceFor []*string `json:"onceFor,omitempty" tf:"once_for,omitempty"`

	// Which incident modes should this workflow run on? By default, workflows only run on standard incidents, but can also be configured to run on test and retrospective incidents.
	// +kubebuilder:validation:Optional
	// +listType=set
	RunsOnIncidentModes []*string `json:"runsOnIncidentModes,omitempty" tf:"runs_on_incident_modes,omitempty"`

	// Which incidents should the workflow be applied to?. Possible values are: `newly_created`, `newly_created_and_active`.
	// +kubebuilder:validation:Optional
	RunsOnIncidents *string `json:"runsOnIncidents,omitempty" tf:"runs_on_incidents,omitempty"`

	// The shortform used to trigger this workflow (only applicable for manual triggers)
	// +kubebuilder:validation:Optional
	Shortform *string `json:"shortform,omitempty" tf:"shortform,omitempty"`

	// What state this workflow is in. Possible values are: `active`, `disabled`, `draft`, `error`.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Steps that are executed as part of the workflow
	// +kubebuilder:validation:Optional
	Steps []StepsParameters `json:"steps,omitempty" tf:"steps,omitempty"`

	// Unique name of the trigger
	// +kubebuilder:validation:Optional
	Trigger *string `json:"trigger,omitempty" tf:"trigger,omitempty"`
}

// WorkflowSpec defines the desired state of Workflow
type WorkflowSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WorkflowParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkflowInitParameters `json:"initProvider,omitempty"`
}

// WorkflowStatus defines the observed state of Workflow.
type WorkflowStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WorkflowObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Workflow is the Schema for the Workflows API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type Workflow struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.conditionGroups) || (has(self.initProvider) && has(self.initProvider.conditionGroups))",message="spec.forProvider.conditionGroups is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.continueOnStepError) || (has(self.initProvider) && has(self.initProvider.continueOnStepError))",message="spec.forProvider.continueOnStepError is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.delay) || (has(self.initProvider) && has(self.initProvider.delay))",message="spec.forProvider.delay is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expressions) || (has(self.initProvider) && has(self.initProvider.expressions))",message="spec.forProvider.expressions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.includePrivateIncidents) || (has(self.initProvider) && has(self.initProvider.includePrivateIncidents))",message="spec.forProvider.includePrivateIncidents is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.onceFor) || (has(self.initProvider) && has(self.initProvider.onceFor))",message="spec.forProvider.onceFor is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.runsOnIncidentModes) || (has(self.initProvider) && has(self.initProvider.runsOnIncidentModes))",message="spec.forProvider.runsOnIncidentModes is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.runsOnIncidents) || (has(self.initProvider) && has(self.initProvider.runsOnIncidents))",message="spec.forProvider.runsOnIncidents is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.state) || (has(self.initProvider) && has(self.initProvider.state))",message="spec.forProvider.state is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.steps) || (has(self.initProvider) && has(self.initProvider.steps))",message="spec.forProvider.steps is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.trigger) || (has(self.initProvider) && has(self.initProvider.trigger))",message="spec.forProvider.trigger is a required parameter"
	Spec   WorkflowSpec   `json:"spec"`
	Status WorkflowStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkflowList contains a list of Workflows
type WorkflowList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Workflow `json:"items"`
}

// Repository type metadata.
var (
	Workflow_Kind             = "Workflow"
	Workflow_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Workflow_Kind}.String()
	Workflow_KindAPIVersion   = Workflow_Kind + "." + CRDGroupVersion.String()
	Workflow_GroupVersionKind = CRDGroupVersion.WithKind(Workflow_Kind)
)

func init() {
	SchemeBuilder.Register(&Workflow{}, &WorkflowList{})
}
