// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/avodah-inc/crossplane-provider-incident-io/apis/alerting/v1alpha1"
	v1alpha1automation "github.com/avodah-inc/crossplane-provider-incident-io/apis/automation/v1alpha1"
	v1alpha1catalog "github.com/avodah-inc/crossplane-provider-incident-io/apis/catalog/v1alpha1"
	v1alpha1incident "github.com/avodah-inc/crossplane-provider-incident-io/apis/incident/v1alpha1"
	v1alpha1oncall "github.com/avodah-inc/crossplane-provider-incident-io/apis/oncall/v1alpha1"
	v1alpha1apis "github.com/avodah-inc/crossplane-provider-incident-io/apis/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1automation.SchemeBuilder.AddToScheme,
		v1alpha1catalog.SchemeBuilder.AddToScheme,
		v1alpha1incident.SchemeBuilder.AddToScheme,
		v1alpha1oncall.SchemeBuilder.AddToScheme,
		v1alpha1apis.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
