// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FieldOptionInitParameters struct {

	// ID of the custom field this option belongs to
	CustomFieldID *string `json:"customFieldId,omitempty" tf:"custom_field_id,omitempty"`

	// Sort key used to order the custom field options correctly
	SortKey *float64 `json:"sortKey,omitempty" tf:"sort_key,omitempty"`

	// Human readable name for the custom field option
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type FieldOptionObservation struct {

	// ID of the custom field this option belongs to
	CustomFieldID *string `json:"customFieldId,omitempty" tf:"custom_field_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Sort key used to order the custom field options correctly
	SortKey *float64 `json:"sortKey,omitempty" tf:"sort_key,omitempty"`

	// Human readable name for the custom field option
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type FieldOptionParameters struct {

	// ID of the custom field this option belongs to
	// +kubebuilder:validation:Optional
	CustomFieldID *string `json:"customFieldId,omitempty" tf:"custom_field_id,omitempty"`

	// Sort key used to order the custom field options correctly
	// +kubebuilder:validation:Optional
	SortKey *float64 `json:"sortKey,omitempty" tf:"sort_key,omitempty"`

	// Human readable name for the custom field option
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

// FieldOptionSpec defines the desired state of FieldOption
type FieldOptionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FieldOptionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FieldOptionInitParameters `json:"initProvider,omitempty"`
}

// FieldOptionStatus defines the observed state of FieldOption.
type FieldOptionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FieldOptionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FieldOption is the Schema for the FieldOptions API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type FieldOption struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.customFieldId) || (has(self.initProvider) && has(self.initProvider.customFieldId))",message="spec.forProvider.customFieldId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.value) || (has(self.initProvider) && has(self.initProvider.value))",message="spec.forProvider.value is a required parameter"
	Spec   FieldOptionSpec   `json:"spec"`
	Status FieldOptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FieldOptionList contains a list of FieldOptions
type FieldOptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FieldOption `json:"items"`
}

// Repository type metadata.
var (
	FieldOption_Kind             = "FieldOption"
	FieldOption_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FieldOption_Kind}.String()
	FieldOption_KindAPIVersion   = FieldOption_Kind + "." + CRDGroupVersion.String()
	FieldOption_GroupVersionKind = CRDGroupVersion.WithKind(FieldOption_Kind)
)

func init() {
	SchemeBuilder.Register(&FieldOption{}, &FieldOptionList{})
}
