// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FieldInitParameters struct {

	// For catalog fields, the ID of the associated catalog type
	CatalogTypeID *string `json:"catalogTypeId,omitempty" tf:"catalog_type_id,omitempty"`

	// Description of the custom field
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Type of custom field. Possible values are: `single_select`, `multi_select`, `text`, `link`, `numeric`.
	FieldType *string `json:"fieldType,omitempty" tf:"field_type,omitempty"`

	FilterBy []FilterByInitParameters `json:"filterBy,omitempty" tf:"filter_by,omitempty"`

	// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
	GroupByCatalogAttributeID *string `json:"groupByCatalogAttributeId,omitempty" tf:"group_by_catalog_attribute_id,omitempty"`

	// Which catalog attribute provides helptext for the options
	HelptextCatalogAttributeID *string `json:"helptextCatalogAttributeId,omitempty" tf:"helptext_catalog_attribute_id,omitempty"`

	// Human readable name for the custom field
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FieldObservation struct {

	// For catalog fields, the ID of the associated catalog type
	CatalogTypeID *string `json:"catalogTypeId,omitempty" tf:"catalog_type_id,omitempty"`

	// Description of the custom field
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Type of custom field. Possible values are: `single_select`, `multi_select`, `text`, `link`, `numeric`.
	FieldType *string `json:"fieldType,omitempty" tf:"field_type,omitempty"`

	FilterBy []FilterByObservation `json:"filterBy,omitempty" tf:"filter_by,omitempty"`

	// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
	GroupByCatalogAttributeID *string `json:"groupByCatalogAttributeId,omitempty" tf:"group_by_catalog_attribute_id,omitempty"`

	// Which catalog attribute provides helptext for the options
	HelptextCatalogAttributeID *string `json:"helptextCatalogAttributeId,omitempty" tf:"helptext_catalog_attribute_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Human readable name for the custom field
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FieldParameters struct {

	// For catalog fields, the ID of the associated catalog type
	// +kubebuilder:validation:Optional
	CatalogTypeID *string `json:"catalogTypeId,omitempty" tf:"catalog_type_id,omitempty"`

	// Description of the custom field
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Type of custom field. Possible values are: `single_select`, `multi_select`, `text`, `link`, `numeric`.
	// +kubebuilder:validation:Optional
	FieldType *string `json:"fieldType,omitempty" tf:"field_type,omitempty"`

	// +kubebuilder:validation:Optional
	FilterBy []FilterByParameters `json:"filterBy,omitempty" tf:"filter_by,omitempty"`

	// For catalog fields, the ID of the attribute used to group catalog entries (if applicable)
	// +kubebuilder:validation:Optional
	GroupByCatalogAttributeID *string `json:"groupByCatalogAttributeId,omitempty" tf:"group_by_catalog_attribute_id,omitempty"`

	// Which catalog attribute provides helptext for the options
	// +kubebuilder:validation:Optional
	HelptextCatalogAttributeID *string `json:"helptextCatalogAttributeId,omitempty" tf:"helptext_catalog_attribute_id,omitempty"`

	// Human readable name for the custom field
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type FilterByInitParameters struct {

	// This must be an attribute of the catalog type of this custom field. It must be an attribute that points to another catalog type (so not a plain string, number, or boolean attribute).
	CatalogAttributeID *string `json:"catalogAttributeId,omitempty" tf:"catalog_attribute_id,omitempty"`

	// This must be the ID of a custom field, which must have values of the same type as the attribute you are filtering by.
	//
	// When this filtering field is set on an incident, the options for this custom field will be filtered to only those with the attribute value that matches the value of the filtering field.
	CustomFieldID *string `json:"customFieldId,omitempty" tf:"custom_field_id,omitempty"`
}

type FilterByObservation struct {

	// This must be an attribute of the catalog type of this custom field. It must be an attribute that points to another catalog type (so not a plain string, number, or boolean attribute).
	CatalogAttributeID *string `json:"catalogAttributeId,omitempty" tf:"catalog_attribute_id,omitempty"`

	// This must be the ID of a custom field, which must have values of the same type as the attribute you are filtering by.
	//
	// When this filtering field is set on an incident, the options for this custom field will be filtered to only those with the attribute value that matches the value of the filtering field.
	CustomFieldID *string `json:"customFieldId,omitempty" tf:"custom_field_id,omitempty"`
}

type FilterByParameters struct {

	// This must be an attribute of the catalog type of this custom field. It must be an attribute that points to another catalog type (so not a plain string, number, or boolean attribute).
	// +kubebuilder:validation:Optional
	CatalogAttributeID *string `json:"catalogAttributeId" tf:"catalog_attribute_id,omitempty"`

	// This must be the ID of a custom field, which must have values of the same type as the attribute you are filtering by.
	//
	// When this filtering field is set on an incident, the options for this custom field will be filtered to only those with the attribute value that matches the value of the filtering field.
	// +kubebuilder:validation:Optional
	CustomFieldID *string `json:"customFieldId" tf:"custom_field_id,omitempty"`
}

// FieldSpec defines the desired state of Field
type FieldSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FieldParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FieldInitParameters `json:"initProvider,omitempty"`
}

// FieldStatus defines the observed state of Field.
type FieldStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FieldObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Field is the Schema for the Fields API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type Field struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fieldType) || (has(self.initProvider) && has(self.initProvider.fieldType))",message="spec.forProvider.fieldType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.filterBy) || (has(self.initProvider) && has(self.initProvider.filterBy))",message="spec.forProvider.filterBy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   FieldSpec   `json:"spec"`
	Status FieldStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FieldList contains a list of Fields
type FieldList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Field `json:"items"`
}

// Repository type metadata.
var (
	Field_Kind             = "Field"
	Field_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Field_Kind}.String()
	Field_KindAPIVersion   = Field_Kind + "." + CRDGroupVersion.String()
	Field_GroupVersionKind = CRDGroupVersion.WithKind(Field_Kind)
)

func init() {
	SchemeBuilder.Register(&Field{}, &FieldList{})
}
