// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Field) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FieldOption) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Role) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Severity) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Status) Hub() {}
