// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Path) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Schedule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Window) Hub() {}
