// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type HandoversInitParameters struct {
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// How often a handover occurs. Possible values are: `hourly`, `daily`, `weekly`.
	IntervalType *string `json:"intervalType,omitempty" tf:"interval_type,omitempty"`
}

type HandoversObservation struct {
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// How often a handover occurs. Possible values are: `hourly`, `daily`, `weekly`.
	IntervalType *string `json:"intervalType,omitempty" tf:"interval_type,omitempty"`
}

type HandoversParameters struct {

	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval" tf:"interval,omitempty"`

	// How often a handover occurs. Possible values are: `hourly`, `daily`, `weekly`.
	// +kubebuilder:validation:Optional
	IntervalType *string `json:"intervalType" tf:"interval_type,omitempty"`
}

type HolidaysPublicConfigInitParameters struct {

	// ISO 3166-1 alpha-2 country codes for the countries that this schedule is configured to view holidays for
	CountryCodes []*string `json:"countryCodes,omitempty" tf:"country_codes,omitempty"`
}

type HolidaysPublicConfigObservation struct {

	// ISO 3166-1 alpha-2 country codes for the countries that this schedule is configured to view holidays for
	CountryCodes []*string `json:"countryCodes,omitempty" tf:"country_codes,omitempty"`
}

type HolidaysPublicConfigParameters struct {

	// ISO 3166-1 alpha-2 country codes for the countries that this schedule is configured to view holidays for
	// +kubebuilder:validation:Optional
	CountryCodes []*string `json:"countryCodes" tf:"country_codes,omitempty"`
}

type LayersInitParameters struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type LayersObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type LayersParameters struct {

	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`
}

type RotationsInitParameters struct {

	// Unique internal ID of the rotation
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Human readable name synced from external provider
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Versions []VersionsInitParameters `json:"versions,omitempty" tf:"versions,omitempty"`
}

type RotationsObservation struct {

	// Unique internal ID of the rotation
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Human readable name synced from external provider
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Versions []VersionsObservation `json:"versions,omitempty" tf:"versions,omitempty"`
}

type RotationsParameters struct {

	// Unique internal ID of the rotation
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// Human readable name synced from external provider
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Versions []VersionsParameters `json:"versions" tf:"versions,omitempty"`
}

type ScheduleInitParameters struct {
	HolidaysPublicConfig []HolidaysPublicConfigInitParameters `json:"holidaysPublicConfig,omitempty" tf:"holidays_public_config,omitempty"`

	// Human readable name synced from external provider
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Rotations []RotationsInitParameters `json:"rotations,omitempty" tf:"rotations,omitempty"`

	// IDs of teams that own this schedule
	// +listType=set
	TeamIds []*string `json:"teamIds,omitempty" tf:"team_ids,omitempty"`

	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

type ScheduleObservation struct {
	HolidaysPublicConfig []HolidaysPublicConfigObservation `json:"holidaysPublicConfig,omitempty" tf:"holidays_public_config,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Human readable name synced from external provider
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Rotations []RotationsObservation `json:"rotations,omitempty" tf:"rotations,omitempty"`

	// IDs of teams that own this schedule
	// +listType=set
	TeamIds []*string `json:"teamIds,omitempty" tf:"team_ids,omitempty"`

	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

type ScheduleParameters struct {

	// +kubebuilder:validation:Optional
	HolidaysPublicConfig []HolidaysPublicConfigParameters `json:"holidaysPublicConfig,omitempty" tf:"holidays_public_config,omitempty"`

	// Human readable name synced from external provider
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Rotations []RotationsParameters `json:"rotations,omitempty" tf:"rotations,omitempty"`

	// IDs of teams that own this schedule
	// +kubebuilder:validation:Optional
	// +listType=set
	TeamIds []*string `json:"teamIds,omitempty" tf:"team_ids,omitempty"`

	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

type VersionsInitParameters struct {

	// When this rotation config will be effective from
	EffectiveFrom *string `json:"effectiveFrom,omitempty" tf:"effective_from,omitempty"`

	// Defines the next moment we'll trigger a handover
	HandoverStartAt *string `json:"handoverStartAt,omitempty" tf:"handover_start_at,omitempty"`

	// Defines the handover intervals for this rota, in order they should apply
	Handovers []HandoversInitParameters `json:"handovers,omitempty" tf:"handovers,omitempty"`

	// Controls how many people are on-call concurrently
	Layers []LayersInitParameters `json:"layers,omitempty" tf:"layers,omitempty"`

	// The incident.io ID of a user
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`

	// Optional restrictions that define when to schedule people for this rota
	WorkingIntervals []WorkingIntervalsInitParameters `json:"workingIntervals,omitempty" tf:"working_intervals,omitempty"`
}

type VersionsObservation struct {

	// When this rotation config will be effective from
	EffectiveFrom *string `json:"effectiveFrom,omitempty" tf:"effective_from,omitempty"`

	// Defines the next moment we'll trigger a handover
	HandoverStartAt *string `json:"handoverStartAt,omitempty" tf:"handover_start_at,omitempty"`

	// Defines the handover intervals for this rota, in order they should apply
	Handovers []HandoversObservation `json:"handovers,omitempty" tf:"handovers,omitempty"`

	// Controls how many people are on-call concurrently
	Layers []LayersObservation `json:"layers,omitempty" tf:"layers,omitempty"`

	// The incident.io ID of a user
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`

	// Optional restrictions that define when to schedule people for this rota
	WorkingIntervals []WorkingIntervalsObservation `json:"workingIntervals,omitempty" tf:"working_intervals,omitempty"`
}

type VersionsParameters struct {

	// When this rotation config will be effective from
	// +kubebuilder:validation:Optional
	EffectiveFrom *string `json:"effectiveFrom,omitempty" tf:"effective_from,omitempty"`

	// Defines the next moment we'll trigger a handover
	// +kubebuilder:validation:Optional
	HandoverStartAt *string `json:"handoverStartAt" tf:"handover_start_at,omitempty"`

	// Defines the handover intervals for this rota, in order they should apply
	// +kubebuilder:validation:Optional
	Handovers []HandoversParameters `json:"handovers" tf:"handovers,omitempty"`

	// Controls how many people are on-call concurrently
	// +kubebuilder:validation:Optional
	Layers []LayersParameters `json:"layers" tf:"layers,omitempty"`

	// The incident.io ID of a user
	// +kubebuilder:validation:Optional
	Users []*string `json:"users" tf:"users,omitempty"`

	// Optional restrictions that define when to schedule people for this rota
	// +kubebuilder:validation:Optional
	WorkingIntervals []WorkingIntervalsParameters `json:"workingIntervals,omitempty" tf:"working_intervals,omitempty"`
}

type WorkingIntervalsInitParameters struct {
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	Weekday *string `json:"weekday,omitempty" tf:"weekday,omitempty"`
}

type WorkingIntervalsObservation struct {
	EndTime *string `json:"endTime,omitempty" tf:"end_time,omitempty"`

	StartTime *string `json:"startTime,omitempty" tf:"start_time,omitempty"`

	Weekday *string `json:"weekday,omitempty" tf:"weekday,omitempty"`
}

type WorkingIntervalsParameters struct {

	// +kubebuilder:validation:Optional
	EndTime *string `json:"endTime" tf:"end_time,omitempty"`

	// +kubebuilder:validation:Optional
	StartTime *string `json:"startTime" tf:"start_time,omitempty"`

	// +kubebuilder:validation:Optional
	Weekday *string `json:"weekday" tf:"weekday,omitempty"`
}

// ScheduleSpec defines the desired state of Schedule
type ScheduleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ScheduleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScheduleInitParameters `json:"initProvider,omitempty"`
}

// ScheduleStatus defines the observed state of Schedule.
type ScheduleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScheduleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Schedule is the Schema for the Schedules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type Schedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.holidaysPublicConfig) || (has(self.initProvider) && has(self.initProvider.holidaysPublicConfig))",message="spec.forProvider.holidaysPublicConfig is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rotations) || (has(self.initProvider) && has(self.initProvider.rotations))",message="spec.forProvider.rotations is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.timezone) || (has(self.initProvider) && has(self.initProvider.timezone))",message="spec.forProvider.timezone is a required parameter"
	Spec   ScheduleSpec   `json:"spec"`
	Status ScheduleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScheduleList contains a list of Schedules
type ScheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Schedule `json:"items"`
}

// Repository type metadata.
var (
	Schedule_Kind             = "Schedule"
	Schedule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Schedule_Kind}.String()
	Schedule_KindAPIVersion   = Schedule_Kind + "." + CRDGroupVersion.String()
	Schedule_GroupVersionKind = CRDGroupVersion.WithKind(Schedule_Kind)
)

func init() {
	SchemeBuilder.Register(&Schedule{}, &ScheduleList{})
}
