// SPDX-FileCopyrightText: 2024 Avodah Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AlertConditionGroupsConditionsInitParameters struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []AlertConditionGroupsConditionsParamBindingsInitParameters `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type AlertConditionGroupsConditionsObservation struct {

	// The logical operation to be applied
	Operation *string `json:"operation,omitempty" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	ParamBindings []AlertConditionGroupsConditionsParamBindingsObservation `json:"paramBindings,omitempty" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	Subject *string `json:"subject,omitempty" tf:"subject,omitempty"`
}

type AlertConditionGroupsConditionsParamBindingsArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AlertConditionGroupsConditionsParamBindingsArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AlertConditionGroupsConditionsParamBindingsArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AlertConditionGroupsConditionsParamBindingsInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []AlertConditionGroupsConditionsParamBindingsArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []AlertConditionGroupsConditionsParamBindingsValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type AlertConditionGroupsConditionsParamBindingsObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []AlertConditionGroupsConditionsParamBindingsArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []AlertConditionGroupsConditionsParamBindingsValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type AlertConditionGroupsConditionsParamBindingsParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []AlertConditionGroupsConditionsParamBindingsArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []AlertConditionGroupsConditionsParamBindingsValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type AlertConditionGroupsConditionsParamBindingsValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AlertConditionGroupsConditionsParamBindingsValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AlertConditionGroupsConditionsParamBindingsValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type AlertConditionGroupsConditionsParameters struct {

	// The logical operation to be applied
	// +kubebuilder:validation:Optional
	Operation *string `json:"operation" tf:"operation,omitempty"`

	// Bindings for the operation parameters
	// +kubebuilder:validation:Optional
	ParamBindings []AlertConditionGroupsConditionsParamBindingsParameters `json:"paramBindings" tf:"param_bindings,omitempty"`

	// The subject of the condition, on which the operation is applied
	// +kubebuilder:validation:Optional
	Subject *string `json:"subject" tf:"subject,omitempty"`
}

type AlertConditionGroupsInitParameters struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []AlertConditionGroupsConditionsInitParameters `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type AlertConditionGroupsObservation struct {

	// The prerequisite conditions that must all be satisfied
	Conditions []AlertConditionGroupsConditionsObservation `json:"conditions,omitempty" tf:"conditions,omitempty"`
}

type AlertConditionGroupsParameters struct {

	// The prerequisite conditions that must all be satisfied
	// +kubebuilder:validation:Optional
	Conditions []AlertConditionGroupsConditionsParameters `json:"conditions" tf:"conditions,omitempty"`
}

type EscalationPathsArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type EscalationPathsArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type EscalationPathsArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type EscalationPathsInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []EscalationPathsArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []EscalationPathsValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type EscalationPathsObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []EscalationPathsArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []EscalationPathsValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type EscalationPathsParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []EscalationPathsArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []EscalationPathsValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type EscalationPathsValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type EscalationPathsValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type EscalationPathsValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type EscalationTargetsInitParameters struct {

	// Escalation paths to route alerts to
	EscalationPaths []EscalationPathsInitParameters `json:"escalationPaths,omitempty" tf:"escalation_paths,omitempty"`

	// Users to notify directly
	Users []UsersInitParameters `json:"users,omitempty" tf:"users,omitempty"`
}

type EscalationTargetsObservation struct {

	// Escalation paths to route alerts to
	EscalationPaths []EscalationPathsObservation `json:"escalationPaths,omitempty" tf:"escalation_paths,omitempty"`

	// Users to notify directly
	Users []UsersObservation `json:"users,omitempty" tf:"users,omitempty"`
}

type EscalationTargetsParameters struct {

	// Escalation paths to route alerts to
	// +kubebuilder:validation:Optional
	EscalationPaths []EscalationPathsParameters `json:"escalationPaths,omitempty" tf:"escalation_paths,omitempty"`

	// Users to notify directly
	// +kubebuilder:validation:Optional
	Users []UsersParameters `json:"users,omitempty" tf:"users,omitempty"`
}

type NotifyChannelsInitParameters struct {

	// The external provider channel ID (e.g. Slack channel ID)
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Human readable name of the channel
	ChannelName *string `json:"channelName,omitempty" tf:"channel_name,omitempty"`

	// The type of channel (e.g. public, private)
	ChannelType *string `json:"channelType,omitempty" tf:"channel_type,omitempty"`
}

type NotifyChannelsObservation struct {

	// The external provider channel ID (e.g. Slack channel ID)
	ChannelID *string `json:"channelId,omitempty" tf:"channel_id,omitempty"`

	// Human readable name of the channel
	ChannelName *string `json:"channelName,omitempty" tf:"channel_name,omitempty"`

	// The type of channel (e.g. public, private)
	ChannelType *string `json:"channelType,omitempty" tf:"channel_type,omitempty"`
}

type NotifyChannelsParameters struct {

	// The external provider channel ID (e.g. Slack channel ID)
	// +kubebuilder:validation:Optional
	ChannelID *string `json:"channelId" tf:"channel_id,omitempty"`

	// Human readable name of the channel
	// +kubebuilder:validation:Optional
	ChannelName *string `json:"channelName,omitempty" tf:"channel_name,omitempty"`

	// The type of channel (e.g. public, private)
	// +kubebuilder:validation:Optional
	ChannelType *string `json:"channelType" tf:"channel_type,omitempty"`
}

type UsersArrayValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type UsersArrayValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type UsersArrayValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type UsersInitParameters struct {

	// The array of literal or reference parameter values
	ArrayValue []UsersArrayValueInitParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []UsersValueInitParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type UsersObservation struct {

	// The array of literal or reference parameter values
	ArrayValue []UsersArrayValueObservation `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	Value []UsersValueObservation `json:"value,omitempty" tf:"value,omitempty"`
}

type UsersParameters struct {

	// The array of literal or reference parameter values
	// +kubebuilder:validation:Optional
	ArrayValue []UsersArrayValueParameters `json:"arrayValue,omitempty" tf:"array_value,omitempty"`

	// The literal or reference parameter value
	// +kubebuilder:validation:Optional
	Value []UsersValueParameters `json:"value,omitempty" tf:"value,omitempty"`
}

type UsersValueInitParameters struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type UsersValueObservation struct {

	// If set, this is the literal value of the step parameter
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type UsersValueParameters struct {

	// If set, this is the literal value of the step parameter
	// +kubebuilder:validation:Optional
	Literal *string `json:"literal,omitempty" tf:"literal,omitempty"`

	// If set, this is the reference into the trigger scope that is the value of this parameter
	// +kubebuilder:validation:Optional
	Reference *string `json:"reference,omitempty" tf:"reference,omitempty"`
}

type WindowInitParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	AlertConditionGroups []AlertConditionGroupsInitParameters `json:"alertConditionGroups,omitempty" tf:"alert_condition_groups,omitempty"`

	// When the maintenance window ends
	EndAt *string `json:"endAt,omitempty" tf:"end_at,omitempty"`

	// If set, alerts matching this window will be escalated to these targets
	EscalationTargets []EscalationTargetsInitParameters `json:"escalationTargets,omitempty" tf:"escalation_targets,omitempty"`

	// If set, alerts matching this window will be automatically attached to this incident
	IncidentID *string `json:"incidentId,omitempty" tf:"incident_id,omitempty"`

	// The incident.io user ID of the lead for this maintenance window
	LeadID *string `json:"leadId,omitempty" tf:"lead_id,omitempty"`

	// Human readable name for the maintenance window
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Custom message included in notifications about this maintenance window
	NotificationMessage *string `json:"notificationMessage,omitempty" tf:"notification_message,omitempty"`

	// Channels to notify about the maintenance window starting and ending
	NotifyChannels []NotifyChannelsInitParameters `json:"notifyChannels,omitempty" tf:"notify_channels,omitempty"`

	// Minutes before the end to send a notification to the configured channels
	NotifyEndMinutesBefore *float64 `json:"notifyEndMinutesBefore,omitempty" tf:"notify_end_minutes_before,omitempty"`

	// Minutes before the start to send a notification to the configured channels
	NotifyStartMinutesBefore *float64 `json:"notifyStartMinutesBefore,omitempty" tf:"notify_start_minutes_before,omitempty"`

	// Whether to retrigger firing alerts through alert routing when the window ends
	RerouteOnEnd *bool `json:"rerouteOnEnd,omitempty" tf:"reroute_on_end,omitempty"`

	// Whether to automatically resolve all firing alerts that matched this window when it ends
	ResolveOnEnd *bool `json:"resolveOnEnd,omitempty" tf:"resolve_on_end,omitempty"`

	// Whether to show this maintenance window in the dashboard sidebar when active
	ShowInSidebar *bool `json:"showInSidebar,omitempty" tf:"show_in_sidebar,omitempty"`

	// When the maintenance window starts
	StartAt *string `json:"startAt,omitempty" tf:"start_at,omitempty"`
}

type WindowObservation struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	AlertConditionGroups []AlertConditionGroupsObservation `json:"alertConditionGroups,omitempty" tf:"alert_condition_groups,omitempty"`

	// When the maintenance window ends
	EndAt *string `json:"endAt,omitempty" tf:"end_at,omitempty"`

	// If set, alerts matching this window will be escalated to these targets
	EscalationTargets []EscalationTargetsObservation `json:"escalationTargets,omitempty" tf:"escalation_targets,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If set, alerts matching this window will be automatically attached to this incident
	IncidentID *string `json:"incidentId,omitempty" tf:"incident_id,omitempty"`

	// The incident.io user ID of the lead for this maintenance window
	LeadID *string `json:"leadId,omitempty" tf:"lead_id,omitempty"`

	// Human readable name for the maintenance window
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Custom message included in notifications about this maintenance window
	NotificationMessage *string `json:"notificationMessage,omitempty" tf:"notification_message,omitempty"`

	// Channels to notify about the maintenance window starting and ending
	NotifyChannels []NotifyChannelsObservation `json:"notifyChannels,omitempty" tf:"notify_channels,omitempty"`

	// Minutes before the end to send a notification to the configured channels
	NotifyEndMinutesBefore *float64 `json:"notifyEndMinutesBefore,omitempty" tf:"notify_end_minutes_before,omitempty"`

	// Minutes before the start to send a notification to the configured channels
	NotifyStartMinutesBefore *float64 `json:"notifyStartMinutesBefore,omitempty" tf:"notify_start_minutes_before,omitempty"`

	// Whether to retrigger firing alerts through alert routing when the window ends
	RerouteOnEnd *bool `json:"rerouteOnEnd,omitempty" tf:"reroute_on_end,omitempty"`

	// Whether to automatically resolve all firing alerts that matched this window when it ends
	ResolveOnEnd *bool `json:"resolveOnEnd,omitempty" tf:"resolve_on_end,omitempty"`

	// Whether to show this maintenance window in the dashboard sidebar when active
	ShowInSidebar *bool `json:"showInSidebar,omitempty" tf:"show_in_sidebar,omitempty"`

	// When the maintenance window starts
	StartAt *string `json:"startAt,omitempty" tf:"start_at,omitempty"`
}

type WindowParameters struct {

	// Groups of prerequisite conditions. All conditions in at least one group must be satisfied
	// +kubebuilder:validation:Optional
	AlertConditionGroups []AlertConditionGroupsParameters `json:"alertConditionGroups,omitempty" tf:"alert_condition_groups,omitempty"`

	// When the maintenance window ends
	// +kubebuilder:validation:Optional
	EndAt *string `json:"endAt,omitempty" tf:"end_at,omitempty"`

	// If set, alerts matching this window will be escalated to these targets
	// +kubebuilder:validation:Optional
	EscalationTargets []EscalationTargetsParameters `json:"escalationTargets,omitempty" tf:"escalation_targets,omitempty"`

	// If set, alerts matching this window will be automatically attached to this incident
	// +kubebuilder:validation:Optional
	IncidentID *string `json:"incidentId,omitempty" tf:"incident_id,omitempty"`

	// The incident.io user ID of the lead for this maintenance window
	// +kubebuilder:validation:Optional
	LeadID *string `json:"leadId,omitempty" tf:"lead_id,omitempty"`

	// Human readable name for the maintenance window
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Custom message included in notifications about this maintenance window
	// +kubebuilder:validation:Optional
	NotificationMessage *string `json:"notificationMessage,omitempty" tf:"notification_message,omitempty"`

	// Channels to notify about the maintenance window starting and ending
	// +kubebuilder:validation:Optional
	NotifyChannels []NotifyChannelsParameters `json:"notifyChannels,omitempty" tf:"notify_channels,omitempty"`

	// Minutes before the end to send a notification to the configured channels
	// +kubebuilder:validation:Optional
	NotifyEndMinutesBefore *float64 `json:"notifyEndMinutesBefore,omitempty" tf:"notify_end_minutes_before,omitempty"`

	// Minutes before the start to send a notification to the configured channels
	// +kubebuilder:validation:Optional
	NotifyStartMinutesBefore *float64 `json:"notifyStartMinutesBefore,omitempty" tf:"notify_start_minutes_before,omitempty"`

	// Whether to retrigger firing alerts through alert routing when the window ends
	// +kubebuilder:validation:Optional
	RerouteOnEnd *bool `json:"rerouteOnEnd,omitempty" tf:"reroute_on_end,omitempty"`

	// Whether to automatically resolve all firing alerts that matched this window when it ends
	// +kubebuilder:validation:Optional
	ResolveOnEnd *bool `json:"resolveOnEnd,omitempty" tf:"resolve_on_end,omitempty"`

	// Whether to show this maintenance window in the dashboard sidebar when active
	// +kubebuilder:validation:Optional
	ShowInSidebar *bool `json:"showInSidebar,omitempty" tf:"show_in_sidebar,omitempty"`

	// When the maintenance window starts
	// +kubebuilder:validation:Optional
	StartAt *string `json:"startAt,omitempty" tf:"start_at,omitempty"`
}

// WindowSpec defines the desired state of Window
type WindowSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WindowParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WindowInitParameters `json:"initProvider,omitempty"`
}

// WindowStatus defines the observed state of Window.
type WindowStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WindowObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Window is the Schema for the Windows API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,incident-io}
type Window struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.alertConditionGroups) || (has(self.initProvider) && has(self.initProvider.alertConditionGroups))",message="spec.forProvider.alertConditionGroups is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endAt) || (has(self.initProvider) && has(self.initProvider.endAt))",message="spec.forProvider.endAt is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.leadId) || (has(self.initProvider) && has(self.initProvider.leadId))",message="spec.forProvider.leadId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.startAt) || (has(self.initProvider) && has(self.initProvider.startAt))",message="spec.forProvider.startAt is a required parameter"
	Spec   WindowSpec   `json:"spec"`
	Status WindowStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WindowList contains a list of Windows
type WindowList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Window `json:"items"`
}

// Repository type metadata.
var (
	Window_Kind             = "Window"
	Window_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Window_Kind}.String()
	Window_KindAPIVersion   = Window_Kind + "." + CRDGroupVersion.String()
	Window_GroupVersionKind = CRDGroupVersion.WithKind(Window_Kind)
)

func init() {
	SchemeBuilder.Register(&Window{}, &WindowList{})
}
